"""Read-only receipt arithmetic and delivery records; no native execution."""
import math
from audit_am import *
def finalize():
    group=policy.GROUPS[2];r=load(STAGE/(group+'-result.json'));p=r['records'][2]['profiles'][1];row=p['frames'][-1];plan=row['proposal'];guard=plan['responseGuard'];contact=guard['support']['contacts'][0]
    angle=math.degrees(math.acos(contact['normal'][1]));threshold=math.cos(p['parameters']['floorAngle'])
    assert row['frame']==550 and row['candidateFault']=='invalid_final_support_normal_or_velocity'
    assert contact['normal'][1]<threshold and contact['velocity']==[0,0,0]
    assert guard['actualFinal']==guard['expectedFinal'] and not guard['passed']
    assert p['appliedUpCount']==1 and p['verifiedLifts']==0 and not p['reached']
    result={'utc':utc(),'nativeSha256':sha(STAGE/(group+'-result.json')),'caseIndex':2,'spec':r['records'][2]['spec'],'frame':550,'fault':row['candidateFault'],'guardSource':'godot/tests/walker_step_up/response_guard.gd:48','supportNormal':contact['normal'],'supportAngleDegrees':angle,'supportUpDot':contact['normal'][1],'requiredUpDot':threshold,'supportVelocity':contact['velocity'],'normalPredicateFailed':True,'velocityPredicateFailed':False,'actualExpectedEndpointDistance':math.dist(guard['actualFinal'],guard['expectedFinal']),'epsilon':guard['epsilon'],'actualSupportPlaneY':contact['point'][1],'canonicalRise':.18,'contactPlaneError':abs(contact['point'][1]-.18),'planeGuardReached':False,'planeQualification':'Arithmetic only; normal failure returned before plane guard','nativeFloorNormal':row['after']['floorNormal'],'nativeFloorAngleDegrees':math.degrees(math.acos(row['after']['floorNormal'][1])),'queryFromEqualsActualTransform':guard['support']['from']==row['after']['transform'],'queryAfterGuardPoseUnchanged':row['telemetry']['afterParent']==row['telemetry']['afterGuard'],'appliedUpCount':1,'verifiedLifts':0,'parentCallsThisResponse':row['lifecycle']['parentCalls'],'reached':False,'along':math.sin(r['records'][2]['spec']['yaw'])*guard['actualFinal'][0]+math.cos(r['records'][2]['spec']['yaw'])*guard['actualFinal'][2],'wholeFrameDelta':row['wholeFrameDelta'],'parentPositionDelta':row['after']['parentPositionDelta'],'parentRealVelocity':row['after']['parentRealVelocity'],'originalProof':row['lifecycle'].get('originalProof'),'fullProposal':plan,'telemetry':row['telemetry'],'engineInternalCauseEstablished':False,'physicalCallCounts':None,'baselineWindows':[],'successfulCandidates':[]}
    for pair in r['records']:
        b=pair['profiles'][0];window=b['frames'][-120:]
        assert len(window)==120 and all(evidence.baseline_target(x,b['target']) and math.dist(x['wholeFrameDelta'],[0,0,0])<.0001 for x in window)
        result['baselineWindows'].append({'caseIndex':pair['caseIndex'],'firstFrame':window[0]['frame'],'lastFrame':window[-1]['frame'],'actualTargetWitnessResponses':120,'maxWholeDistance':max(math.dist(x['wholeFrameDelta'],[0,0,0]) for x in window)})
        c=pair['profiles'][1]
        if c['status']!='completed':continue
        assert evidence.profile(c,pair['spec'],group,True)
        lifts=[x for x in c['frames'] if x['appliedUpCount']]
        result['successfulCandidates'].append({'caseIndex':pair['caseIndex'],'spec':pair['spec'],'applied':c['appliedUpCount'],'verified':c['verifiedLifts'],'liftFrames':[x['frame'] for x in lifts],'maxEndpointError':max(math.dist(x['proposal']['responseGuard']['actualFinal'],x['proposal']['responseGuard']['expectedFinal']) for x in lifts),'finalFrame':c['frames'][-1]['frame'],'ordinaryLandingStreak':c['ordinaryLandingStreak'],'finalSupport':c['finalSupport']})
    write(OUT/'failure-analysis.json',result)
    write(OUT/(group+'-owner-inspection.json'),{'utc':utc(),'checkpointSha256':sha(OUT/(group+'-checkpoint.json')),'detailSha256':sha(OUT/(group+'-detail.json')),'failureAnalysisSha256':sha(OUT/'failure-analysis.json'),'passed':False,'nextAuthorizedGroup':None,'review':'Whole group FAIL. First .42/.18 candidate normal fails explicit46-degree support test despite exact endpoint and zero collider velocity. One lift applied but not verified; no arrival. Remaining +45 pair unrun. No retry, correction, fallback or further execution.','AMReleaseSha256':sha(OUT/'AM-release.json')})
    groups=[]
    for g,exitcode in zip(policy.GROUPS,[0,0,1]):
        s=load(STAGE/(g+'-supervisor.json'));cp=load(OUT/(g+'-checkpoint.json'))
        groups.append({'group':g,'invocations':1,'supervisorCommandExit':exitcode,'nativeExit':s['returnCode'],'argv':s['argv'],'owned':s['owned'],'nativeSha256':cp['nativeSha256'],'supervisorSha256':cp['supervisorSha256'],'dependenciesSha256':cp['dependenciesSha256'],'logSha256':cp['logSha256'],'checkpointSha256':sha(OUT/(g+'-checkpoint.json')),'ownerInspectionSha256':sha(OUT/(g+'-owner-inspection.json')),'lockAcquiredUnix':s['lockAcquiredUnix'],'lockReleasePendingUnix':s['lockReleasePendingUnix'],'passed':cp['passed'],'counts':cp['counts']})
    write(OUT/'execution-record.json',{'utc':utc(),'grant':'MOTH-BLENDER-20261004-AM','base':'3dcdbb27','branch':'astra/walker-calibrated-admission-am','authorization':load(OUT/'authorization.json'),'groups':groups,'nativeInvocations':3,'standaloneParserInvocations':0,'retries':0,'sourceEdits':0,'delegatedChildren':0,'queuedWork':False,'release':load(OUT/'AM-release.json'),'postReleaseTests':{'command':"python3 -B -m unittest discover -s tools/godot-multiplayer/new-maps/walker-calibrated-admission -p 'test_*.py'",'passed':30,'logSha256':sha(OUT/'post-release-tests.log'),'qualification':'Offline Python only; does not waive native failure'},'nativeStepAdmission':False,'candidateAdmission':False,'productionPromotion':False,'productionMotionAccountingOpen':True,'candidateMapJourneysUnrun':60,'staticVesperFailuresUnresolved':184,'physicalCallCounts':None,'helperIncident':'inspect_am wrote negative detail successfully then summary printing raised missing json import; helper import fixed only, no native rerun.'})
if __name__=='__main__':finalize()
