import {createHash} from 'node:crypto';
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';

export const SOURCE_SHA256='2905696af09ccace8c2dbb384139748ef80146be25bbbe75bf8111d28dc146e8';
const original="function actorHit(o,d,a,max){const s=Number.isFinite(a.hitScale)&&a.hitScale>0?a.hitScale:1;return boxHit(o,d,{x:a.x,z:a.z,w:.85*s,d:.85*s,h:1.8*s},max);}";
const replacement=`function actorHit(o,d,a,max){
 const h=a.isNpc===true?a.npcHitVolume:null;
 if(h&&Number.isFinite(h.width)&&h.width>=.1&&h.width<=4&&Number.isFinite(h.depth)&&h.depth>=.1&&h.depth<=4&&Number.isFinite(h.bottom)&&h.bottom>=0&&Number.isFinite(h.top)&&h.top>h.bottom&&h.top<=4){
  return boxHit(v(o.x,o.y-h.bottom,o.z),d,{x:a.x,z:a.z,w:h.width,d:h.depth,h:h.top-h.bottom},max);
 }
 const s=Number.isFinite(a.hitScale)&&a.hitScale>0?a.hitScale:1;return boxHit(o,d,{x:a.x,z:a.z,w:.85*s,d:.85*s,h:1.8*s},max);
}`;
export function generateCampaignCore(source) {
  const hash=createHash('sha256').update(source).digest('hex');
  if(hash!==SOURCE_SHA256)throw new Error(`Locked core drift: expected ${SOURCE_SHA256}, got ${hash}`);
  if(source.split(original).length!==2)throw new Error('Expected exactly one source actorHit');
  let imports=0;
  const rewritten=source.replace(/from '\.\/([a-z0-9-]+\.mjs)'/g,(_match,file)=>{imports++;return `from '../../game/${file}'`;});
  if(imports!==34)throw new Error('Source relative import set changed');
  return `// GENERATED by port/native-campaign/generate-core.mjs; DO NOT EDIT.\n// Source game/core.mjs SHA256 ${SOURCE_SHA256}; only imports and actorHit differ.\n`+
    rewritten.replace(original,replacement);
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  const source=readFileSync(new URL('../../game/core.mjs',import.meta.url),'utf8');
  writeFileSync(new URL('./core.generated.mjs',import.meta.url),generateCampaignCore(source));
}
