import {createHash} from 'node:crypto';
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';

export const SOURCE_SHA256='58ff1b9c7467a53da00638f16edfd3df2e1e6fd06480ff081ad13c88fb64bdb9';
const original="function actorHit(o,d,a,max){const s=Number.isFinite(a.hitScale)&&a.hitScale>0?a.hitScale:1;return boxHit(o,d,{x:a.x,z:a.z,w:.85*s,d:.85*s,h:1.8*s},max);}";
const replacement=`function actorHit(o,d,a,max){
 const h=a.isNpc===true?a.npcHitVolume:null;
 if(h&&Number.isFinite(h.width)&&h.width>=.1&&h.width<=4&&Number.isFinite(h.depth)&&h.depth>=.1&&h.depth<=4&&Number.isFinite(h.bottom)&&h.bottom>=0&&Number.isFinite(h.top)&&h.top>h.bottom&&h.top<=4){
  const yaw=Number.isFinite(a.bodyYaw)?a.bodyYaw:0,c=Math.cos(yaw),s=Math.sin(yaw),dx=o.x-a.x,dz=o.z-a.z;
  const cast=q=>boxHit(v(c*dx-s*dz,o.y-q.bottom,s*dx+c*dz),v(c*d.x-s*d.z,d.y,s*d.x+c*d.z),{x:q.offsetX||0,z:q.offsetZ||0,w:q.width,d:q.depth,h:q.top-q.bottom},max);
  const q=h.shield,validShield=q&&Number.isFinite(q.width)&&q.width>=.1&&q.width<=2&&Number.isFinite(q.depth)&&q.depth>=.1&&q.depth<=2&&Number.isFinite(q.bottom)&&q.bottom>=0&&Number.isFinite(q.top)&&q.top>q.bottom&&q.top<=4&&Number.isFinite(q.offsetX)&&Math.abs(q.offsetX)<=2&&Number.isFinite(q.offsetZ)&&Math.abs(q.offsetZ)<=2;
  const body=cast(h),shield=a.npcShield&&validShield?cast(q):null;
  return body===null?shield:shield===null?body:Math.min(body,shield);
 }
 const s=Number.isFinite(a.hitScale)&&a.hitScale>0?a.hitScale:1;return boxHit(o,d,{x:a.x,z:a.z,w:.85*s,d:.85*s,h:1.8*s},max);
}`;
export function generateCampaignCore(source) {
  const hash=createHash('sha256').update(source).digest('hex');
  if(hash!==SOURCE_SHA256)throw new Error(`Locked core drift: expected ${SOURCE_SHA256}, got ${hash}`);
  if(source.split(original).length!==2)throw new Error('Expected exactly one source actorHit');
  let imports=0;
  const rewritten=source.replace(/from '\.\/([a-z0-9-]+\.mjs)'/g,(_match,file)=>{imports++;return `from '../../game/${file}'`;});
  if(imports!==34)throw new Error('Source relative import set changed');
  // Source integration deliberately reads global WEAPONS, bypassing weaponFor.
  // This single audited hook keeps its swept collision/gravity/cover algorithm.
  const before='baseWeapon=WEAPONS[r.weapon??1],w=altSpec?';
  const after='baseWeapon=this.projectileWeapon?.(r)??WEAPONS[r.weapon??1],w=altSpec?';
  if(rewritten.split(before).length!==2)throw new Error('Expected one projectile weapon lookup');
  // A camera-selected candidate behind muzzle cover is not an actor contact.
  // Correct event classification only; the source clear/damage decision stays.
  const candidate='hit:target?.id??vehicleTarget?.id??sentryTarget?.id??false,falloff';
  const confirmed='hit:clear?(target?.id??vehicleTarget?.id??sentryTarget?.id??false):false,falloff';
  if(rewritten.split(candidate).length!==3)throw new Error('Expected primary and alt candidate events');
  return `// GENERATED by port/native-campaign/generate-core.mjs; DO NOT EDIT.\n// Source game/core.mjs SHA256 ${SOURCE_SHA256}; only imports, actorHit, projectile weapon lookup and blocked-shot event classification differ.\n`+
    rewritten.replace(original,replacement).replace(before,after).replaceAll(candidate,confirmed);
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  const source=readFileSync(new URL('../../game/core.mjs',import.meta.url),'utf8');
  const output=new URL('./core.generated.mjs',import.meta.url), generated=generateCampaignCore(source);
  if(process.argv.includes('--check')) {
    if(readFileSync(output,'utf8')!==generated)throw new Error('Campaign core adapter is stale');
  } else writeFileSync(output,generated);
}
