import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {DESTINATION_MAPS} from '../../game/destination-maps.mjs';
import {MAPS} from '../../game/maps.mjs';
import {PROTOCOL_VERSION,SNAPSHOT_DELTA_VERSION} from '../../game/protocol.mjs';
const git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim();
const source='51289b79c627a26a381ba556b92bab71f93f3732';
const base='6b6368b16d9c17ef57f2d26792703a70427c5a32';
if(git('rev-parse',`${source}^{commit}`)!==source)throw Error('Missing pinned source');
const comparison=process.argv[2];
if(!comparison)throw Error('Supply isolated comparison worktree');
const previous=JSON.parse(execFileSync(process.execPath,['--input-type=module','-e',"import {MAPS} from './game/maps.mjs'; console.log(JSON.stringify(MAPS.map(m=>m.id)))"],{cwd:comparison,encoding:'utf8'}));
if(execFileSync('git',['rev-parse','HEAD'],{cwd:comparison,encoding:'utf8'}).trim()!==base)throw Error('Wrong comparison revision');
const added=MAPS.filter(m=>!previous.includes(m.id)).map(m=>m.id);
const ids=DESTINATION_MAPS.map(m=>m.id);
if(JSON.stringify([...added].sort())!==JSON.stringify([...ids].sort()))throw Error('Registry delta differs from destination collection');
const files=git('diff','--name-only',base,source).split('\n');
const maps=DESTINATION_MAPS.map(m=>({id:m.id,name:m.name,source_file:files.find(f=>f.startsWith('game/destination-')&&f.endsWith('-maps.mjs')&&readFileSync(f,'utf8').includes(`'${m.id}'`)),relevant_commit:'3cda7d666b7c702361bad2674486bb0a229780c3',supported_modes:m.arena.play,distinctive_features:{description:m.description,landmarks:m.landmarks??[],vehicles:m.vehicles?.length??0,traversal:m.traversal?.length??0},required_assets_status:'pending visual resource-closure audit'}));
for(const m of maps)if(!m.source_file)throw Error(`No source for ${m.id}`);
const write=(path,data)=>{mkdirSync(path.slice(0,path.lastIndexOf('/')),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n');};
write('port/contracts/source-lock.json',{schema_version:1,repository:'mojomast/cocs',audit_base_commit:'e79fcc048d7d97e7418d2e6fdbdd304b69362fa0',source_branch:'main',source_commit:source,comparison_base_commit:base,audited_lineage_merge_base:git('merge-base','e79fcc048d7d97e7418d2e6fdbdd304b69362fa0',source),selection_status:'selected_v8.8_destinations',map_ids:ids,godot_version:'4.5.2.stable.official.6ce3de25a'});
write('port/contracts/map-selection.json',{schema_version:1,source_commit:source,maps});
write('port/contracts/protocol.json',{schema_version:1,protocol_version:PROTOCOL_VERSION,snapshot_delta_version:SNAPSHOT_DELTA_VERSION,advertised_delta:0,simulation_hz:60,snapshot_hz:30,prediction:false});
write('port/reports/intake.json',{source_commit:source,comparison_base_commit:base,base_registry_ids:previous,target_registry_ids:MAPS.map(m=>m.id),new_ids:added,changed_files:files,unregistered_destination_ids:ids.filter(id=>!MAPS.some(m=>m.id===id)),tools:{node:process.version},shared_boundary_changes:git('diff','--stat','e79fcc048d7d97e7418d2e6fdbdd304b69362fa0',source,'--','game','server')});
console.log(`Pinned ${source}; ${ids.length} newly registered destinations; protocol ${PROTOCOL_VERSION}`);
