extends SceneTree

const Weather = preload("res://ambience/weather_service.gd")
const Scenery = preload("res://moth_scenery/scenery.gd")
const Manager = preload("res://combat_particles/manager.gd")

func _initialize() -> void:
	call_deferred("_verify")

func _verify() -> void:
	var service := Weather.new()
	root.add_child(service)
	service.bind({"id": "test-snow", "biome": "snow"}, null, "playing", 1)
	service.apply_snapshot({"time": 8.5, "singlePlayer": {"weather": "snow"}})
	assert(service.wants_precipitation_handoff())
	assert(service.diagnostics().authoritative_time)
	service.tick(0.05)
	assert(service.diagnostics().elapsed == 8.5, "presentation delta must not advance authoritative weather")
	assert(service.diagnostics().particles == 0, "no precipitation before handoff")
	service.set_native_weather_suppressed(true)
	service.apply_settings({"weather_enabled": false})
	assert(not service.wants_precipitation_handoff(), "weather off releases native visual ownership")
	service.apply_settings({"weather_enabled": true, "weather_quality": 0})
	assert(not service.wants_precipitation_handoff())
	service.apply_settings({"weather_quality": 100, "reduced_motion": true})
	assert(not service.wants_precipitation_handoff())
	service.apply_settings({"reduced_motion": false})
	assert(service.wants_precipitation_handoff())
	service.set_native_weather_suppressed(false)
	assert(service.diagnostics().particles == 0)
	var manager := Manager.new()
	assert(manager.set_weather_precipitation_suppressed(true))
	assert(manager.set_weather_precipitation_suppressed(false))
	manager.free()
	var scenery := Scenery.new()
	assert(scenery.set_weather_precipitation_suppressed(true))
	assert(scenery.set_weather_precipitation_suppressed(false))
	scenery.free()
	service.free()
	print("WEATHER_OWNERSHIP_OK")
	quit()
