// Deterministic native palette, derived exclusively from the source catalog.
import {WEAPON_FINISHES} from '../../game/cosmetics.mjs';
import {Color} from 'three';
import {createHash} from 'node:crypto';
import {readFile, writeFile} from 'node:fs/promises';

const root = new URL('../../', import.meta.url);
const source = await readFile(new URL('game/cosmetics.mjs', root));
const hash = createHash('sha256').update(source).digest('hex');
const renderer = await readFile(new URL('game/view.mjs', root));
const rendererHash = createHash('sha256').update(renderer).digest('hex');
const entries = Object.fromEntries(WEAPON_FINISHES.map(({id, name, description, level, colors}) => {
  const roles = {dark: colors.secondary, light: colors.accent, glow: colors.primary};
  return [id, {name, description, level, ...roles, linear: Object.fromEntries(Object.entries(roles).map(([role, hex]) => {
    const c = new Color(hex); // Source Three.js renderer's sRGB-to-linear conversion.
    return [role, [c.r, c.g, c.b]];
  }))}];
}));
const output = `extends RefCounted\n# Generated by tools/godot-weapons/finishes.mjs from game/cosmetics.mjs.\n# Source renderer game/view.mjs: dark=secondary, light=accent, glow=primary.\nconst SOURCE_SHA256 = "${hash}"\nconst RENDERER_SHA256 = "${rendererHash}"\nconst PALETTES = ${JSON.stringify(entries, null, '\t')}\n`;
const target = new URL('godot/first_person/generated/finishes.gd', root);
if (process.argv.slice(2).includes('--check')) {
  const existing = await readFile(target, 'utf8').catch(() => null);
  if (existing !== output) throw new Error('Native finish catalog stale; run node tools/godot-weapons/finishes.mjs');
  console.log(`Native finish catalog current (${hash}; view ${rendererHash})`);
} else {
  await writeFile(target, output);
  console.log(`Generated ${WEAPON_FINISHES.length} source finishes (${hash}; view ${rendererHash})`);
}
