extends SceneTree
const Controller = preload("res://combat_shields/controller.gd")
var failed := false
var assertions := 0
var fx: Node3D

func check(value: bool, message: String) -> void:
	assertions += 1
	if not value:
		failed = true
		push_error("COMBAT_SHIELDS: " + message)

func _initialize() -> void: call_deferred("run")

func actor(id: int, extra: Dictionary = {}) -> Dictionary:
	var a := {"id":id,"x":float(id % 8) * 2.0,"y":0.0,"z":-5.0,"health":100.0,"armor":30.0,"dead":0.0,"grounded":true,"yaw":0.0,"baseHeight":1.8}
	a.merge(extra, true)
	return a

func state(actors: Array) -> Dictionary: return {"actors":actors,"time":1.0,"mapId":"test"}

func run() -> void:
	fx = Controller.new()
	root.add_child(fx)
	fx.set_process(false)
	fx.configure(null)
	var data: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://tests/combat_shields/source.json"))
	var initial: Dictionary = data.frames[1].snapshot.state
	var original := JSON.stringify(initial)
	fx.apply_state(initial, 0)
	check(fx.debug_state().kinds[1] == "temporary shield", "executed source overshield pool")
	fx.apply_events(data.frames[2].events.items, 0)
	check(fx.counters.ripples == 1, "genuine source damage ripple")
	fx.apply_events(data.frames[2].events.items, 0)
	check(fx.counters.ripples == 1, "duplicate numeric event cannot retrigger")
	fx.apply_events(data.frames[3].events.items, 0)
	fx.apply_state(data.frames[3].snapshot.state, 0)
	check(fx.counters.shatters == 1, "damage event plus armor snapshot produce ONE shatter")
	check(fx.debug_state().kinds[1] == "", "unexpired powerup timer does not manufacture depleted protection")
	fx.apply_state(data.frames[4].snapshot.state, 0)
	fx.apply_events(data.frames[4].events.items, 0)
	check(fx.counters.recovery == 1, "real health delta and pickup coalesce recovery")
	check(JSON.stringify(initial) == original, "input authoritative dictionaries unchanged")
	fx.reset()
	fx.apply_events(data.frames[5].events.items, 0)
	fx._process(0.05)
	check(fx.pending.size() == 1, "initial events survive before first snapshot")
	fx.apply_state(data.frames[5].snapshot.state, 0)
	check(fx.counters.phase == 1, "source spawn resolves queued actor")
	check(fx.debug_state().kinds[1] == "spawn protection", "actual source protection seconds")
	fx.reset()
	fx.apply_state(data.horde.snapshot.state, 0)
	check(fx.debug_state().kinds[21] == "directional damage reduction", "actual source Horde bulwark profile")
	check(fx.tracks[21].slot.material.get_shader_parameter("directional") == 1.0, "NPC frontal cone uniform")
	fx.reset()
	fx.apply_state(data.dash.snapshot.state,-1)
	fx.apply_events(data.dash.events.items,-1)
	check(fx.counters.dash == 1 and fx.debug_state().active_bursts == 4, "actual source cline dash creates bounded phase trail")
	for map: Dictionary in data.maps:
		fx.reset()
		fx.apply_state({"mapId":map.mapId,"actors":[map.actor]}, -1)
		check(fx.tracks.size() == 1, "actual map actor shape " + map.mapId)
	check(Controller.protection_kind({"active":10,"powerups":{"overshield":20},"armor":0}) == "", "active is not invulnerability")
	check(Controller.protection_kind({"health":200,"maxHealth":100}) == "", "overhealth is not a shield")
	check(Controller.protection_kind({"verbState":{"verb":"alignment-review","active":true,"pool":20,"poolIn":2}}) == "alignment absorb pool", "review exact source snapshot")
	fx.reset()
	var many: Array = []
	for id in range(16): many.append(actor(id))
	fx.apply_state(state(many), 0)
	check(fx.tracks.size() == 16 and fx.debug_state().visible_shells == 15, "16 actors and local first-person shell excluded")
	var material_ids := {}
	for track: Dictionary in fx.tracks.values():
		if not track.slot.is_empty(): material_ids[track.slot.material.get_instance_id()] = true
	check(material_ids.size() == 15, "independent materials for the 15 eligible remote actors")
	check(fx.tracks[0].slot.is_empty(), "local actor observed without reserving a render slot")
	for id in range(1,17):
		fx.apply_events([{"id":id,"sourceId":"same-pad","type":"teleport","actor":1,"from":{"x":1,"y":1,"z":-5},"to":{"x":5,"y":1,"z":-5}}],0)
	check(fx.counters.events == 16 and fx.bursts.size() <= 16, "equal Horde source IDs retain distinct numeric wire events; pool bounded")
	fx.apply_events([{"id":1,"type":"damage","actor":1,"amount":20},{"id":"swarm","type":"damage","actor":1,"amount":20},{"id":NAN,"type":"damage","actor":1,"amount":20}],0)
	check(fx.counters.events == 16, "duplicates string and nonfinite IDs rejected")
	for id in range(17,2200): fx.apply_events([{"id":id,"type":"damage","actor":1,"source":2,"amount":1}],0)
	check(fx.seen.size() <= 2048 and fx.debug_state().materials <= 48, "dedup window and material registrations bounded")
	fx.apply_events([{"id":1,"type":"damage","actor":1,"amount":20}],0)
	check(fx.seen.size() <= 2048, "evicted old event cannot re-enter")
	var refs: Array[WeakRef] = []
	for slot: Dictionary in fx.slots + fx.bursts: refs.append(weakref(slot.material))
	fx.set_quality("low")
	check(fx.debug_state().materials <= 24 and fx.factory.state().materials <= 24, "low quality shrinks live registrations")
	fx._process(1.1)
	check(fx.tracks.is_empty() and fx.debug_state().active_bursts == 0, "stale state hides all effects")
	fx.reset()
	check(fx.factory.state().materials == 0, "reset releases factory registrations")
	for ref: WeakRef in refs: check(ref.get_ref() == null, "material lifetime ends on reset")
	fx.apply_state(state([actor(1),actor(2,{"x":NAN}),actor(3,{"y":INF})]),0)
	check(fx.tracks.size() == 1, "malformed coordinates cannot enter render transforms")
	fx.set_suspended(true)
	var stopped: float = fx.clock
	fx._process(0.5)
	fx.apply_state(state([actor(1)]),0)
	check(fx.clock == stopped and fx.tracks.is_empty(), "focus suspension pauses and hides")
	fx.set_suspended(false)
	fx.apply_state(state([actor(1)]),0)
	fx.apply_state({"over":true},0)
	fx.apply_state(state([actor(1)]),0)
	check(fx.tracks.is_empty(), "results latched until round reset")
	fx.reset()
	fx.apply_state(state([actor(1)]),0)
	fx.apply_state(state([]),0)
	check(fx.tracks.is_empty(), "departed identity released immediately")
	fx.reset()
	fx.apply_state(state([actor(1)]),0)
	fx.apply_events([{"id":1,"type":"damage","actor":1,"source":1,"amount":5}],0)
	fx.reset()
	fx.apply_state(state([actor(1)]),0)
	fx.apply_events([{"id":1,"type":"damage","actor":1,"source":1,"amount":5}],0)
	check(fx.counters.ripples == 1, "wire IDs restart after reset")
	fx.reset()
	fx.apply_state(state([actor(1,{"yaw":PI/2}),actor(2,{"x":4.0})]),0)
	fx.apply_events([{"id":1,"type":"damage","actor":1,"source":2,"amount":5}],0)
	var direction: Vector3 = fx.tracks[1].slot.material.get_shader_parameter("hit_direction")
	check(direction.distance_to(Vector3(0,0,1)) < 0.001, "attacker direction transformed into actor shell local space")
	fx.apply_events([{"id":2,"type":"damage","actor":1,"amount":5}],0)
	check(fx.tracks[1].slot.material.get_shader_parameter("hit_direction_known") == false, "unknown attacker uses neutral pulse, not invented direction")
	fx.apply_state(state([actor(1,{"grounded":false,"vy":4.0})]),0)
	check(fx.debug_state().active_bursts == 1, "observed grounded-to-rising transition gives jump phase")
	fx.apply_state(state([actor(1,{"grounded":false,"vy":4.0})]),0)
	check(fx.debug_state().active_bursts == 1, "repeated airborne state does not respawn jump effect")
	fx.apply_state(state([actor(1,{"health":0,"dead":2})]),0)
	check(fx.debug_state().visible_shells == 0 and fx.debug_state().active_bursts == 0, "death removes persistent and transient coverage")
	fx.apply_state(state([actor(1)]),0)
	check(fx.counters.phase == 1, "observed dead-to-alive creates one respawn phase")
	fx.reset()
	for id in range(80): fx.apply_events([{"id":id,"type":"spawn","actor":99}],0)
	check(fx.pending.size() == 64, "pre-snapshot event queue bounded")
	fx._process(0.8)
	check(fx.pending.is_empty(), "unknown actor events expire without ghost spawns")
	fx.reset()
	fx.apply_state(state([actor(1)]),0)
	fx.apply_events([{"id":50,"type":"damage","actor":1,"amount":5}],0)
	fx.apply_state({"actors":[actor(1)],"time":0.0,"mapId":"test"},0)
	check(fx.seen.is_empty(), "source clock regression resets prior round sequence")
	var visual := Node3D.new()
	root.add_child(visual)
	visual.position = Vector3(7,0.9,-8)
	var anchors := {1:visual}
	fx.bind_actor_visuals(anchors)
	fx._process(0.01)
	check(fx.tracks[1].slot.node.global_position == visual.global_position, "shell follows read-only interpolated presentation anchor")
	check(fx.tracks[1].position != visual.global_position, "render anchor does not rewrite authoritative track position")
	visual.free()
	anchors.clear()
	fx._process(0.01)
	check(fx.tracks[1].slot.node.position == fx.tracks[1].position, "removed render anchor safely falls back to source pose")
	fx.free()
	print("COMBAT_SHIELDS_%s assertions=%d" % ["OK" if not failed else "FAIL", assertions])
	quit(1 if failed else 0)
