extends SceneTree
## Future engine-granted gate. Exercises the real mapper with real InputEvents.
const Router = preload("res://fighting/presentation/input_router.gd")
const Camera = preload("res://fighting/presentation/camera.gd")
const DeviceChoices = preload("res://fighting/presentation/device_choices.gd")
var failures: Array = []

func _initialize() -> void:
	var choices := Router.new()
	_check(choices.assign(0,DeviceChoices.model(choices.devices,0,[0,1]).next),"P1 first pad through ordinary choice")
	_check(choices.assign(1,DeviceChoices.model(choices.devices,1,[0,1]).next),"P2 skips owned pad through ordinary choice")
	_check(choices.devices == [0,1],"ordinary P1 then P2 gets distinct pads")
	_pad(choices,0,JOY_BUTTON_X,true)
	_pad(choices,1,JOY_BUTTON_Y,true)
	choices.unplug(0) # Mapper unit boundary, not a claimed hardware disconnect.
	_check(choices.down == [{},{}] and choices.queued == [0,0],"disconnect clears BOTH actors and both tap latches")
	_check(choices.command(0).held == 0 and choices.command(1).held == 0,"both actors released on disconnect")
	var missing := DeviceChoices.model(choices.devices,0,[1])
	_check(DeviceChoices.caption(missing,0,{}).contains("disconnected"),"missing assignment caption is truthful")
	_check(not DeviceChoices.caption(missing,0,{}).begins_with("Keyboard"),"missing controller never impersonates Keyboard")
	_check(choices.devices == [0,1],"caption refresh never changes route")
	_pad(choices,0,JOY_BUTTON_X,true)
	_pad(choices,1,JOY_BUTTON_Y,true)
	_check(choices.command(0).held == 0 and choices.command(1).held == 0,"reconnection cannot repeat either held attack")
	_pad(choices,0,JOY_BUTTON_X,false); _pad(choices,1,JOY_BUTTON_Y,false)
	_pad(choices,0,JOY_BUTTON_X,true); _pad(choices,1,JOY_BUTTON_Y,true)
	_check(choices.command(0).held == 1 and choices.command(1).held == 2,"both players rearm only after release and fresh press")
	_check(choices.assign(0,int(missing.next)) and choices.devices == [-1,1],"one public choice recovers Keyboard without transferring P2")
	_check(choices.command(1).held == 0,"reassignment releases other actor too")
	_check(not choices.assign(-1,4) and not choices.assign(2,4) and not choices.assign(0,-2),"invalid assignment boundaries rejected")
	var tap_router := Router.new()
	_key(tap_router,KEY_F,true); _key(tap_router,KEY_F,false)
	var tap := tap_router.command(0)
	_check(tap.held == 1 and tap.pressed == 1,"subtick tap occupies one core-held sample")
	_check(tap_router.command(0).held == 0,"subtick tap releases on following sample")
	_key(tap_router,KEY_C,true); _key(tap_router,KEY_C,false)
	_check(tap_router.command(0).held == 64,"subtick guard lasts one sample")
	_check(tap_router.command(0).held == 0,"guard release never becomes sticky")
	_key(tap_router,KEY_F,true); _key(tap_router,KEY_F,false)
	tap_router.set_modal(true); tap_router.set_modal(false)
	_check(tap_router.command(0).held == 0,"modal clears unconsumed tap latch")
	_key(tap_router,KEY_F,true)
	tap_router.release_all()
	_key(tap_router,KEY_F,true)
	_check(tap_router.command(0).held == 0,"focus release requires fresh physical press")
	_key(tap_router,KEY_F,false); _key(tap_router,KEY_F,true)
	_check(tap_router.command(0).held == 1,"fresh press rearms held-history edge")
	var pad_tap := Router.new()
	pad_tap.assign(0,4)
	_pad(pad_tap,4,JOY_BUTTON_LEFT_SHOULDER,true)
	_pad(pad_tap,4,JOY_BUTTON_RIGHT_SHOULDER,true)
	_pad(pad_tap,4,JOY_BUTTON_LEFT_SHOULDER,false)
	_pad(pad_tap,4,JOY_BUTTON_RIGHT_SHOULDER,false)
	_check((int(pad_tap.command(0).held)&256) != 0,"subtick super chord survives held-history core")
	_check(pad_tap.command(0).held == 0,"subtick super chord releases next sample")
	_pad(pad_tap,4,JOY_BUTTON_X,true); _pad(pad_tap,4,JOY_BUTTON_X,false)
	pad_tap.unplug(4)
	_check(pad_tap.command(0).held == 0,"unplug clears pending short tap")
	var router := Router.new()
	_key(router,KEY_F,true)
	_check(router.command(0).pressed == 1,"first light edge")
	_check(router.command(0).pressed == 0,"held light never repeats")
	_key(router,KEY_F,false)
	_key(router,KEY_C,true)
	_check(router.command(0).held == 64,"independent immediate guard")
	_key(router,KEY_A,true); _key(router,KEY_D,true)
	_key(router,KEY_W,true); _key(router,KEY_S,true)
	var neutral := router.command(0)
	_check(neutral.axis_x == 0 and neutral.axis_y == 0,"horizontal and vertical SOCD neutral")
	router.set_modal(true)
	_check(router.command(0).held == 0,"modal release clears held")
	router.set_modal(false)
	_key(router,KEY_C,true)
	_check(router.command(0).held == 0,"fresh press required after modal")
	_key(router,KEY_C,false); _key(router,KEY_C,true)
	_check(router.command(0).pressed == 64,"release then press rearms")
	router.release_all()
	_check(router.assign(0,7),"pad device assignment")
	_check(not router.assign(1,7),"pad cannot own both players")
	_pad(router,8,JOY_BUTTON_X,true)
	_check(router.command(0).held == 0,"foreign device ignored")
	_pad(router,7,JOY_BUTTON_X,true)
	_check(router.command(0).pressed == 1,"owned device accepted")
	_check(router.command(1).pressed == 0,"other player not controlled")
	router.unplug(7)
	_check(router.command(0).held == 0,"unplug releases")
	_pad(router,7,JOY_BUTTON_X,false)
	_pad(router,7,JOY_BUTTON_LEFT_SHOULDER,true)
	_pad(router,7,JOY_BUTTON_RIGHT_SHOULDER,true)
	_check((router.command(0).pressed & 256) == 256,"controller super chord")
	var motion := InputEventJoypadMotion.new()
	motion.device = 7; motion.axis = JOY_AXIS_LEFT_X; motion.axis_value = 0.1
	router.ingest(motion)
	_check(router.command(0).axis_x == 0,"stick deadzone")
	motion.axis_value = 0.8; router.ingest(motion)
	_check(router.command(0).axis_x == 1,"stick quantized")
	_check(not router.rebind(0,"L",KEY_ESCAPE),"Esc reserved")
	_check(not router.rebind(0,"L",KEY_F12),"F12 reserved")
	_check(not router.rebind(0,"L",KEY_J),"cross-layout duplicate rejected")
	_check(router.rebind(0,"L",KEY_Z),"editable physical binding")
	router.path = "user://fighting/input-gate.json"
	router.document = {"future_option":{"retain":true}}
	_check(router.save_settings() == OK,"isolated binding save")
	var restored := Router.new()
	restored.path = router.path; restored.load_settings()
	_check(restored.bindings[0].L == KEY_Z,"binding roundtrip")
	_check(restored.document.future_option.retain,"unknown fields retained")
	DirAccess.remove_absolute(router.path)
	for aspect: float in [760.0/520.0,1280.0/800.0,1920.0/1080.0]:
		for left: int in range(-8000,8001,1000):
			for right: int in range(left,8001,1000):
				var frame := Camera.framing([{"x":left},{"x":right}],aspect)
				# Rect2/Vector3 store float32 coordinates. Use the same 10-micrometre
				# numerical epsilon as camera_gate.gd, not exact float64 boundaries.
				_check(float(left)/1000.0-1.6 >= frame.center.x-frame.height*aspect*0.5-0.00001,"left silhouette framed")
				_check(float(right)/1000.0+1.6 <= frame.center.x+frame.height*aspect*0.5+0.00001,"right silhouette framed")
	print("FIGHTING_INPUT_GATE ",JSON.stringify({"passed":failures.is_empty(),"failures":failures}))
	quit(0 if failures.is_empty() else 1)

func _key(router: RefCounted, code: int, pressed: bool) -> void:
	var event := InputEventKey.new()
	event.physical_keycode = code; event.pressed = pressed
	router.ingest(event)

func _pad(router: RefCounted, device: int, code: int, pressed: bool) -> void:
	var event := InputEventJoypadButton.new()
	event.device = device; event.button_index = code; event.pressed = pressed
	router.ingest(event)

func _check(value: bool, message: String) -> void:
	if not value: failures.append(message)
