// Original fighting content. Generation expands explicit authored tables; no combat authority.
import { CHARACTERS } from '../../../game/data.mjs';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../../../', import.meta.url));
const keys = ['stand_l','stand_m','stand_h','crouch_l','crouch_m','crouch_h','air_l','air_m','air_h'];
// Per normal: startup, active, recovery, damage, hitstun, blockstun, forward reach(mm).
const profiles = {
 chatgpt: {stats:[1000,52,100,185], archetype:'all-rounder', resource:['adaptation',0,3,0],
  names:['Survey Tap','Cage Cross','Plasma Lift','Floor Probe','Cable Sweep','Survey Scoop','Bracket Peck','Open-Cage Kick','Descending Frame'],
  poses:['square lead-hand snap','opposed shoulder cross','two-arm rising cage','kneeling fingertip probe','low cable-guided shin arc','wide scoop from crouch','tucked aerial hand','open hip side kick','both forearms descend'],
  n:[[5,3,10,48,20,12,660],[8,3,16,78,25,16,930],[12,4,23,112,31,19,1100],[5,2,11,45,19,11,590],[9,3,18,74,26,15,1020],[11,4,24,105,33,18,880],[5,3,9,47,20,12,600],[8,4,14,76,26,16,900],[11,5,20,110,32,19,1050]],
  throws:['Adaptive Turn','Cable Exchange'], super:'Closed-Loop Verdict'},
 claude: {stats:[1060,44,110,170], archetype:'ward footsies', resource:['review',0,4,0],
  names:['Crook Jab','Chevron Check','Ceramic Lance','Ward Knuckle','Shin Gate','Shield Rise','Glide Palm','Winged Ward','Descending Chevron'],
  poses:['crooked elbow jab behind ward','shield-first horizontal check','long braced palm lance','closed kneeling knuckle','shield edge skims shin','forearms rise as nested shields','one palm checks below gliding torso','two broad forearms spread','closed chevron falls shoulder-first'],
  n:[[6,3,12,51,22,14,760],[10,4,18,84,29,18,1150],[15,3,26,120,35,20,1480],[6,2,12,49,21,12,660],[10,4,20,80,29,17,1170],[13,5,25,114,35,20,1000],[6,4,11,50,22,14,700],[10,5,17,83,29,18,1050],[14,4,23,118,35,20,1230]],
  throws:['Ward Pivot','Review Reversal'], super:'Layered Injunction'},
 grok: {stats:[980,57,95,205], archetype:'pressure brawler', resource:['heat',0,6,0],
  names:['Offset Hook','Piston Elbow','Outrider Hammer','Oil-Rig Tap','Raking Boot','Furnace Upper','Crooked Peck','Flying Piston','Falling Anvil'],
  poses:['short asymmetric hook','rear elbow drives hip-first','one heavy arm folds overhead','off-center knuckle below knee','heel scrapes in crooked arc','compressed rear arm bursts upward','one tucked hand hooks down','rear elbow leads airborne body','single arm slams with bent knees'],
  n:[[4,3,12,50,21,11,610],[7,4,18,86,27,15,900],[18,3,27,128,36,20,1050],[5,2,12,47,20,11,560],[8,3,19,82,28,15,950],[10,4,25,118,34,18,810],[4,3,10,49,21,11,570],[7,4,16,85,28,16,850],[12,4,22,125,35,19,960]],
  throws:['Heat Hitch','Outrider Spin'], super:'Redline Pileup'},
 meta: {stats:[1100,40,120,165], archetype:'armored grappler', resource:['brace',0,3,3],
  names:['Turbine Jab','Plating Shoulder','Twin-Piston Crush','Rivet Tap','Foundation Kick','Anchor Lift','Turbine Peck','Cross-Brace Knee','Two-Drum Drop'],
  poses:['broad planted fist','hip drives layered shoulder','two arms crush from raised brace','low rivet-hand tap','heavy low heel with planted hips','both turbines lift from squat','compact airborne fist','crossed arms brace a knee','both arms drop with tucked spine'],
  n:[[7,3,14,58,24,14,690],[11,4,23,98,32,18,1040],[17,5,31,130,39,23,1180],[7,2,14,54,23,13,620],[12,4,24,92,32,18,1110],[15,5,30,126,39,22,970],[7,3,12,56,24,14,650],[11,5,20,96,32,18,980],[16,6,27,129,39,23,1120]],
  throws:['Turbine Fold','Counterweight Cast'], super:'Twin-Core Collapse'},
 gemini: {stats:[960,56,95,192], archetype:'two-stance duelist', resource:['band',0,1,0],
  names:['Petal Jab','Twin-Claw Cross','Rail Palm Lift','Split Tap','Petal Scissor','Bifurcate Rise','Claw Peck','Mirror Heel','Petal Guillotine'],
  poses:['split fingers lead alternate shoulders','crossed claw forearms','open palm drives bifurcated hips','two fingers reach from kneel','opposed low shin scissor','palms unfurl upward','one claw below tucked hips','mirrored heel extends from twist','two petals close downward'],
  n:[[5,2,10,46,20,12,670],[8,3,15,75,25,16,990],[12,4,22,108,32,19,1130],[5,2,10,45,19,11,610],[8,3,17,72,26,15,1040],[11,4,23,104,33,18,900],[5,3,9,46,20,12,620],[8,4,13,74,26,16,940],[11,4,19,107,32,19,1040]],
  throws:['Petal Exchange','Mirror Revision'], super:'Bifurcated Horizon'},
 deepseek: {stats:[1080,42,115,175], archetype:'charge hover zoner', resource:['fuel',0,90,90],
  names:['Sleeve Jab','Pressure Palm','Vessel Elbow','Valve Tap','Ballast Sweep','Compression Lift','Diver Peck','Pressure Knee','Salvage Dive'],
  poses:['compact sleeve-driven fist','palms vent from tucked ribs','diver elbow lifts pressure vessel','closed valve knuckle at ankle','weighted shin drags low','compressed arms open upward','tight fist beneath tucked chest','knee rises with vented hips','both elbows dive from compact tuck'],
  n:[[7,3,13,55,23,13,720],[11,4,21,91,31,18,1130],[16,4,29,126,38,22,1250],[7,2,13,52,22,12,650],[11,4,23,88,31,17,1190],[14,5,28,121,38,21,1020],[7,4,12,53,23,13,680],[11,5,19,90,31,18,1080],[15,5,25,124,38,22,1180]],
  throws:['Ballast Clamp','Vessel Inversion'], super:'Critical Compression'},
 mistral: {stats:[920,62,85,198], archetype:'air-dash rushdown', resource:['air_dash',0,1,1],
  names:['Scatter Snap','Aerofoil Heel','Rising Cyclone','Slip Tap','Wing Sweep','Tailfin Rise','Slipstream Peck','Swept Heel','Sirocco Dive'],
  poses:['lean fingertip snap','long swept roundhouse','whole-body spiral kick','low open-hand tap','shin traces aerofoil arc','rear heel rises with winged arms','narrow aerial jab','extended swept heel from lean','diagonal kick below trailing arms'],
  n:[[4,2,9,45,19,11,580],[7,3,14,72,24,15,970],[10,4,22,105,31,18,1060],[4,2,10,45,19,10,530],[7,3,16,70,25,14,1030],[10,4,22,101,32,17,840],[4,3,8,45,19,11,550],[7,4,12,71,25,15,920],[10,4,18,104,31,18,1020]],
  throws:['Slipstream Fold','Leeward Cast'], super:'Nine-Gust Break'},
 kimi: {stats:[900,58,85,190], archetype:'blink mobile zoner', resource:['context',0,3,0],
  names:['Gimbal Jab','Orbital Backhand','Apogee Kick','Orbit Tap','Perigee Sweep','Axis Rise','Satellite Peck','Orbit Heel','Falling Meridian'],
  poses:['rotating wrist jab','full orbital backhand','high gimbal heel from torso rotation','wrist circles below knee','shin draws low orbit','both hands spiral upward','orbiting palm below hips','heel traces a horizontal ring','gimbal arm arcs down past bent knee'],
  n:[[5,3,11,46,21,12,710],[9,3,18,77,27,17,1190],[14,4,25,111,34,20,1400],[5,2,12,45,20,11,640],[9,3,20,74,28,16,1240],[12,4,25,107,35,19,980],[5,4,10,46,21,12,670],[9,4,16,76,28,17,1110],[13,5,22,110,34,20,1300]],
  throws:['Context Orbit','Gimbal Exchange'], super:'Closed Context Eclipse'},
 qwen: {stats:[1020,48,105,180], archetype:'anchor setplay grappler', resource:['tools',0,3,3],
  names:['Lamellar Tap','Cable-Guided Palm','Sentinel Lift','Lockpin Tap','Segment Sweep','Layered Rise','Glyph Peck','Locking Heel','Falling Lamella'],
  poses:['sequential plate knuckle','rope guides open palm','layered forearms lift sentinel torso','small lockpin fist at shin','low segmented cable arm','stacked forearms unfold upward','measured airborne palm','grounded torso twists into heel','layers close into descending elbow'],
  n:[[6,3,12,52,22,13,780],[9,4,19,85,29,17,1180],[14,4,27,119,36,21,1310],[6,2,13,50,21,12,700],[10,4,21,82,29,16,1250],[13,5,26,115,37,20,1060],[6,3,11,51,22,13,730],[9,5,17,84,29,17,1120],[13,5,23,117,36,21,1230]],
  throws:['Tool Lock','Sentinel Transfer'], super:'Final Toolchain'}
};
const projectile = (spawn,range,vx,y=1000,extra={}) => ({spawn_frame:spawn,x:450,y,vx,vy:0,gravity:0,w:350,h:300,life:Math.ceil(range/vx),range,max_count:1,clash_strength:1,pierce:false,...extra});
const movement = (type,from,to,vx,vy,distance,duration,extra={}) => ({type,from,to,vx,vy,distance,duration,air_only:false,ground_only:false,cooldown:45,invulnerable_from:-1,invulnerable_to:-1,...extra});
const specialRows = {
 chatgpt:[['Survey Orb','projectile',12,3,22,85,30,18,1000,{projectile:projectile(12,5000,170)},'Slow survey sphere controls 5 m; jump it or punish the release.'],['Cable Reel','strike',14,4,24,90,34,18,2600,{movement:movement('reel',14,17,90,0,1300,15)},'Articulated cable pulls on contact; crouch guard then punish its long recoil.'],['Adaptive Throw','throw',12,2,30,145,0,0,790,{},'Telegraphed close command capture; jump during the cage opening.']],
 claude:[['Ward Lance','strike',14,3,27,105,34,19,3100,{},'Braced ceramic thrust reaches 3.1 m; crouch guard and whiff punish the planted recovery.'],['Safety Glide','mobility',6,18,14,0,0,0,0,{movement:movement('glide',6,23,-65,-25,1400,18,{air_only:true})},'Slow airborne retreat preserves spacing; intercept from below or meet the landing.'],['Review Capture','counter',5,12,30,135,0,0,850,{counter:{from:5,to:16,reflect:true,strike:true,range:850,damage_frame:25,release_frame:40}},'Timed ward reflects projectiles and captures close strikes; throw it or wait for the ward to close.']],
 grok:[['Arc Grenade','projectile',16,3,24,95,32,18,1000,{projectile:projectile(16,3800,110,1250,{vy:100,gravity:8,w:420,h:420,life:45})},'Arcing piston grenade pressures a landing; advance beneath it or challenge its startup.'],['Charged Super Jump','mobility',8,1,16,0,0,0,0,{movement:movement('super_jump',8,8,60,255,1800,35,{ground_only:true}),input:{simple:'MOBILITY',motion:'[2]8',charge_frames:18,charge_axis:'down'}},'Hold down for 18 ticks before the compressed leap; anti-air its predictable rise.'],['Rocket Tackle','strike',17,5,29,150,36,20,1100,{movement:movement('reel',8,21,100,0,1800,14),armor:{from:8,to:16,hits:1,damage_percent:100}},'Armored piston rush ends in a shoulder impact; block then punish, or throw the startup.']],
 meta:[['Shock Cone','strike',11,5,25,100,33,18,2200,{},'Short twin-sector cone stops approaches; bait the 2.2 m limit and punish recovery.'],['Brace Slam','strike',12,6,30,145,38,22,1200,{movement:movement('slam',4,17,25,-180,900,14,{air_only:true}),knockdown_frames:42},'Airborne braced drop controls a compact landing; move away then punish the deep squat.'],['Twin Grab','throw',15,2,34,180,0,0,980,{armor:{from:7,to:13,hits:1,damage_percent:100}},'Longest heavy squeeze has visible turbine windup; jump or interrupt before armor.']],
 gemini:[['Rail Lance','projectile',13,2,25,90,31,18,1000,{projectile:projectile(13,5700,260,1100,{clash_strength:2})},'Narrow finite lance checks 5.7 m; crouch under its tall line or jump on anticipation.'],['Band Transition','mobility',5,1,12,0,0,0,0,{movement:movement('double_jump',5,5,30,180,1000,25,{air_only:true}),stance:{resource:'band',set:1,duration:180,variants:{stand_l:'palm_l',stand_m:'palm_m',stand_h:'palm_h'}}},'One extra airborne impulse opens palm stance for 180 ticks; attack its visible ascent.'],['Revision Grab','throw',13,2,29,140,0,0,780,{stance:{resource:'band',set:1,duration:180,variants:{stand_l:'palm_l',stand_m:'palm_m',stand_h:'palm_h'}}},'Petal capture sets palm stance; escape with jump before the petals close.']],
 deepseek:[['Compute Shot','projectile',10,3,28,130,36,21,1000,{projectile:projectile(10,6200,190,950,{w:500,h:440,clash_strength:3}),input:{simple:'SPECIAL',motion:'[4]6',charge_frames:36,charge_axis:'back'}},'Requires 36 back-held ticks; large compression shell travels 6.2 m, so pressure before charge completes.'],['Hover Jets','mobility',5,30,18,0,0,0,0,{movement:movement('hover',5,34,25,0,800,30,{air_only:true}),resource_effect:{resource:'fuel',cost:30,gain:0,on:'start',reset_on_land:true}},'Each hover spends 30 of 90 fuel and lasts 30 ticks; wait below and contest the fuel-limited landing.'],['Vessel Crush','throw',16,2,35,170,0,0,900,{armor:{from:8,to:14,hits:1,damage_percent:100}},'Armored pressure clamp is slow and grounded; jump it or strike before the vessel braces.']],
 mistral:[['Flak Fan','strike',10,4,20,80,29,16,1900,{},'Short aerofoil fan confirms close pressure; stay beyond 1.9 m and punish the sweep.'],['Air Dash','mobility',3,10,13,0,0,0,0,{movement:movement('air_dash',3,12,145,0,1450,10,{air_only:true}),resource_effect:{resource:'air_dash',cost:1,gain:0,on:'start',reset_on_land:true}},'One 1.45 m airborne burst per landing; guard high and intercept its landing rather than chasing.'],['Slide Takedown','strike',14,5,27,125,34,18,1150,{level:'low',movement:movement('reel',5,18,105,0,1500,14),knockdown_frames:36},'Low sliding heel sweeps into a hard fall; crouch guard and punish the extended finish.']],
 kimi:[['Context Pulse','projectile',15,2,27,95,32,18,1000,{projectile:projectile(15,6600,300,1100,{w:260,h:220})},'Finite narrow rail pulse covers 6.6 m; duck its line or force recovery with a jump.'],['Blink Step','mobility',15,1,22,0,0,0,0,{movement:movement('blink',15,15,0,0,1800,1,{ground_only:true,cooldown:75})},'Visible 15-tick gimbal windup precedes a 1.8 m forward blink; attack the arrival, with no hidden invulnerability.'],['Context Grab','throw',14,2,32,135,0,0,800,{},'Orbital capture trades damage for repositioning; jump the open-ring windup.']],
 qwen:[['Tool Pulse','projectile',14,3,24,90,32,18,1000,{projectile:projectile(14,4800,180,850,{w:380,h:340})},'Segmented tool pulse controls midrange; jump it and punish the sentinel release.'],['Tether Anchor','mobility',20,1,25,0,0,0,0,{movement:movement('anchor',20,20,0,0,2000,1,{ground_only:true,cooldown:90,anchor_life:180,trigger_range:650,pull_speed:55,max_count:1}),resource_effect:{resource:'tools',cost:1,gain:0,on:'start',reset_on_land:false}},'One visible anchor lasts 180 ticks and pulls once within 0.65 m; jump over its trigger or pressure the setup.'],['Tool Throw','throw',14,2,33,155,0,0,1050,{},'Long cable capture has a 14-tick lock glyph; jump or interrupt while the cable unfolds.']]
};
function strike(name,kind,s,a,r,d,hs,bs,reach,id,key,extra={}) {
 const level=key.startsWith('crouch_')?'low':key.startsWith('air_')||key==='stand_h'&&id==='grok'?'overhead':kind==='throw'||kind==='counter'?'unblockable':'mid';
 const air=key.startsWith('air_');
 return {name,kind,startup:s,active:a,recovery:r,damage:d,hitstun:hs,blockstun:bs,hitstop:d?Math.min(12,5+Math.floor(d/30)):0,level,animation:key,effect:`${id}:${key}`,hitboxes:reach&&kind!=='projectile'&&kind!=='counter'?[{from:s,to:s+a-1,x:250,y:key.startsWith('crouch_')?150:air?-450:900,w:reach-250,h:key.startsWith('crouch_')?420:air?750:600}]:[],cancels:[],meter_cost:kind==='super'?1000:0,meter_gain:d?Math.min(90,Math.floor(d/2)):0,chip:kind==='projectile'?8:0,pushback:Math.round(d*2),launch_velocity:0,juggle_cost:1,air_ok:air,ground_ok:!air,...extra};
}
function cancel(move,target,on=['hit','block'],offset=0) {move.cancels.push({to:target,from:move.startup+offset,until:move.startup+move.active+Math.min(move.recovery,8)-1,on});}
const operators = CHARACTERS.map(source=>{
 const id=source.id,p=profiles[id],moves={};
 keys.forEach((key,i)=>{
  moves[key]=strike(p.names[i],'strike',...p.n[i],id,key);
  moves[key].description=`${p.poses[i]}; ${key.startsWith('air_')?'airborne overhead':key.startsWith('crouch_')?'low-line grounded strike':'standing space check'}.`;
  moves[key].counterplay=i%3===0?'Guard its short reach, then challenge a delayed follow-up.':i%3===1?'Block at its preferred range; whiff punish the extended limb.':'Respect the rising contact, then punish the committed recovery.';
  moves[key].input={simple:['L','M','H'][i%3],motion:key.startsWith('crouch_')?'2':key.startsWith('air_')?'j.':'5'};
  if(i%3===2){moves[key].launch_velocity=155+(id==='meta'?15:0);moves[key].juggle_cost=2;}
  if(i%3===0)cancel(moves[key],keys[i+1]);
  if(i%3===1){cancel(moves[key],keys[i+1]);cancel(moves[key],'special1',['hit']);}
  if(i%3===2)cancel(moves[key],'super',['hit']);
 });
 if(id==='meta')moves.stand_h.armor={from:8,to:16,hits:1,damage_percent:100};
 ['throw_f','throw_b'].forEach((key,i)=>{
  const s=6+(id==='meta'?2:0),damage=120+Math.floor((p.stats[0]-900)/10)+(i?8:0);
  moves[key]=strike(p.throws[i],'throw',s,2,30+i*2,damage,0,0,750,id,key,{throw:{range:750,tech_frames:10,damage_frame:s+12,release_frame:s+23,victim_x:600,victim_y:0,side_swap:!!i,command:false,ground_only:true,knockdown_frames:36},input:{simple:i?'BACK_GRAB':'GRAB',motion:i?'4+Grab':'Grab'},description:i?'Paired pivot casts the victim behind the attacker.':'Paired grip casts the victim forward.',counterplay:'Press Grab within ten ticks to tech, or jump before capture.'});
 });
 specialRows[id].forEach((row,i)=>{
  const [name,kind,s,a,r,d,hs,bs,reach,extra,description]=row,key=`special${i+1}`;
  moves[key]=strike(name,kind,s,a,r,d,hs,bs,reach,id,key,{input:{simple:['SPECIAL','MOBILITY','SPECIAL_GRAB'][i],motion:['236','22','63214'][i]},...extra,description,counterplay:description.split(';').at(-1).trim()});
  if(extra.movement?.air_only){moves[key].air_ok=true;moves[key].ground_ok=false;}
  if(['air_dash','double_jump'].includes(extra.movement?.type)){moves[key].movement.air_uses=1;moves[key].movement.reset_on_land=true;}
  if(id==='chatgpt'&&i===1){moves[key].movement.vx=0;moves[key].movement.pull_speed=90;moves[key].movement.on='hit';}
  if(['grok','mistral'].includes(id)&&i===2){moves[key].movement.type='rush';moves[key].movement.ground_only=true;}
  if(kind==='throw')moves[key].throw={range:reach,tech_frames:0,damage_frame:s+8,release_frame:s+22,victim_x:Math.min(650,reach),victim_y:0,side_swap:id==='kimi',command:true,ground_only:true,knockdown_frames:42};
  if(kind==='mobility'&&extra.movement?.air_only)cancel(moves[key],'air_m',['whiff'],Math.min(a-1,2));
 });
 if(id==='grok')moves.special3.resource_effect={resource:'heat',cost:0,gain:2,on:'hit',reset_on_land:false};
 if(id==='chatgpt')moves.special1.resource_effect={resource:'adaptation',cost:0,gain:1,on:'hit',reset_on_land:false};
 if(id==='claude')moves.special3.resource_effect={resource:'review',cost:0,gain:1,on:'hit',reset_on_land:false};
 if(id==='kimi')moves.special1.resource_effect={resource:'context',cost:0,gain:1,on:'hit',reset_on_land:false};
 moves.super=strike(p.super,'super',9+Object.keys(profiles).indexOf(id),5,42,240+Object.keys(profiles).indexOf(id)*6,45,25,2400,id,'super',{input:{simple:'SUPER',motion:'236236'},knockdown_frames:54,description:`${p.archetype} payoff: ${p.poses[2]} expands into a committed signature finish. Costs the full 1000 meter.`,counterplay:'Guard the anticipated finish; punish 42 recovery ticks if it misses.'});
 if(id==='gemini'){
  [['palm_l','Open-Petal Check',6,3,12,52,23,14,840],['palm_m','Mirror Lance',10,3,19,87,30,18,1280],['palm_h','Horizon Palm',15,4,28,121,37,21,1450]].forEach(([key,name,...numbers])=>{moves[key]=strike(name,'strike',...numbers,id,key,{input:{simple:['L','M','H'][key.at(-1)==='l'?0:key.at(-1)==='m'?1:2],motion:'palm stance'},description:'Open-palm stance replaces claw contraction with a long planted ceramic thrust.',counterplay:'Palm stance extends reach but exposes slower recovery; attack its transition.'});});
  cancel(moves.palm_l,'palm_m');cancel(moves.palm_m,'palm_h');cancel(moves.palm_m,'special1',['hit']);cancel(moves.palm_h,'super',['hit']);
 }
 const trace=(route)=>{
  let tick=0;return route.map((key,index)=>{const m=moves[key];const sample={tick,axis_x:0,axis_y:key.startsWith('crouch_')?-1:0,held:{L:1,M:2,H:4,SPECIAL:8,MOBILITY:16,SPECIAL_GRAB:40,SUPER:256}[m.input.simple],pressed:{L:1,M:2,H:4,SPECIAL:8,MOBILITY:16,SPECIAL_GRAB:40,SUPER:256}[m.input.simple],move:key};tick+=m.startup+m.hitstop+1;return sample;});
 };
 const basicRoutes={chatgpt:['stand_l','stand_m','stand_h'],claude:['stand_l','crouch_m','stand_h'],grok:['stand_l','stand_m','crouch_h'],meta:['crouch_l','crouch_m','stand_h'],gemini:['stand_l','stand_m','stand_h'],deepseek:['crouch_l','stand_m','stand_h'],mistral:['stand_l','crouch_m','crouch_h'],kimi:['stand_l','stand_m','crouch_h'],qwen:['crouch_l','crouch_m','stand_h']};
 const specialRoutes={chatgpt:['stand_l','stand_m','special1'],claude:['stand_l','crouch_m','special1'],grok:['stand_l','stand_m','special1'],meta:['crouch_l','crouch_m','special1'],gemini:['stand_l','stand_m','special1'],deepseek:['crouch_l','crouch_m','special1'],mistral:['stand_l','crouch_m','special1'],kimi:['stand_l','stand_m','special1'],qwen:['crouch_l','crouch_m','special1']};
 const airProjectile=['chatgpt','gemini','kimi','qwen'].includes(id);
 const routes=[basicRoutes[id],specialRoutes[id],['air_l','air_m',airProjectile?'special1':'air_h']];
 if(airProjectile)moves.special1.air_ok=true;
 for(const route of routes)route.slice(1).forEach((to,i)=>{const from=moves[route[i]];if(!from.cancels.some(c=>c.to===to))cancel(from,to,['hit']);});
 return {id,name:source.name,archetype:p.archetype,stats:{hp:p.stats[0],walk_speed:p.stats[1],weight:p.stats[2],jump_velocity:p.stats[3],height:1800},resource:{id:p.resource[0],min:p.resource[1],max:p.resource[2],initial:p.resource[3],regen_ground_per_tick:id==='deepseek'?1:0,regen_interval:id==='qwen'?120:0,reset_on_round:true},moves,combos:routes.map((route,i)=>{
  const inputs=trace(route),charged=id==='deepseek'&&i===1;
  if(charged){inputs.forEach(sample=>{sample.tick+=36;});inputs.forEach((sample,j)=>{sample.axis_x=j===2?1:-1;if(j<2)sample.duration=inputs[j+1].tick-sample.tick;});}
  return {name:['Basic confirm','Signature special confirm','Air corner chain'][i],route,setup_inputs:charged?[{tick:0,axis_x:-1,axis_y:0,held:0,pressed:0,duration:36}]:[],inputs,status:'proposed',preconditions:{distance:i===2?500:550,attacker_y:i===2?1000:0,defender_y:i===2?800:0,corner:i===2,meter:0,charge_back_ticks:0},notes:'Training fixture places actors as specified; charge setup uses real inputs. Schedule estimates first-active-frame contacts and shared hitstop. Native core must verify positions, contact, stun continuity, scaling and landing; not runtime proof.'};
 })};
});
const rules={version:1,tick_rate:60,units_per_meter:1000,round_seconds:99,rounds_to_win:2,stage_half_width:8000,seed:20261002,buffer_frames:6,throw_tech_frames:10,meter_max:1000,gravity:9,terminal_velocity:300,jump_startup:4,landing_recovery:4,spawn_distance:3000,round_intro_frames:90,round_over_frames:120,guard_release_frames:0,air_guard:false,socd:'neutral_both_axes',negative_edge:false,wakeup_invulnerability_frames:8,throw_invulnerability_frames:12,combo_limits:{max_hits:12,juggle_budget:8,wall_bounces:1,ground_bounces:1,otg_hits:1,damage_scaling_percent:[100,90,80,70,60,50,40,35,30,25,20,20],damage_floor_percent:20,hitstun_deterioration_per_hit:2,min_hitstun:6},hurtboxes:{stand:{x:-300,y:0,w:600,h:1800},crouch:{x:-340,y:0,w:680,h:1050},air:{x:-300,y:100,w:600,h:1400}},pushbox:{x:-330,y:0,w:660,h:1600},input_help:{notation:'5 neutral, 2 down, 4 back, 6 forward, 8 up; j. airborne; xx cancel; [4] hold back. Directions mirror facing.',simple:'L/M/H normals; Special S1; Mobility S2; Special+Grab S3; Super costs 1000. Grab throw, Back+Grab back throw.',guard:'Independent Guard high; Down+Guard low. Back alone walks. No RMB tap/hold split.'}};
const states='idle walk_f walk_b crouch jump_rise jump_apex jump_fall land dash_f dash_b guard_hi guard_lo hit_hi hit_lo hit_air block_hi block_lo knockdown wakeup throw_tech win lose'.split(' ');
const pairs=operators.flatMap(op=>Object.entries(op.moves).filter(([,m])=>m.throw||m.counter).map(([key,m])=>({attacker:op.id,move:key,clip:`victim_${op.id}_${key}`,contact:m.startup,damage:m.throw?.damage_frame??m.counter.damage_frame,release:m.throw?.release_frame??m.counter.release_frame,victim_x:m.throw?.victim_x??600,victim_y:0,side_swap:m.throw?.side_swap??false,socket_attacker:'Socket_GripR',socket_victim:'Socket_Chest',contact_tolerance_mm:60})));
const manifest={version:1,status:'authoring requirements; assets not built or accepted',fps:60,root_policy:'locked; simulation owns all travel',operators:operators.map(op=>({id:op.id,glb:`res://fighting/assets/operators/${op.id}.glb`,motion_brief:`${op.archetype}; neutral, gait, guard and reactions must preserve the posture vocabulary of ${profiles[op.id].poses.join('; ')}. Fully author each clip; common names do not permit shared recolored libraries.`,states,combat:Object.entries(op.moves).map(([key,m])=>({clip:key,frames:m.startup+m.active+m.recovery,contact_windows:m.hitboxes.map(b=>[b.from,b.to]),projectile_spawn:m.projectile?.spawn_frame??null,movement_window:m.movement?[m.movement.from,m.movement.to]:null,counter_window:m.counter?[m.counter.from,m.counter.to]:null,authored_motion:m.description,effect:m.effect})),victim_clips:pairs.map(p=>p.clip)})),paired_timelines:pairs};
const estimateRows=operators.flatMap(op=>op.combos.map(combo=>{
 const edges=combo.route.slice(1).map((key,i)=>{const a=op.moves[combo.route[i]],b=op.moves[key],elapsed=combo.inputs[i+1].tick-combo.inputs[i].tick-a.hitstop;return {from:combo.route[i],to:key,cancel_frame:elapsed,contact_delay:elapsed-a.startup+b.startup,available_hitstun:a.hitstun-rules.combo_limits.hitstun_deterioration_per_hit*i,estimated_slack:a.hitstun-rules.combo_limits.hitstun_deterioration_per_hit*i-(elapsed-a.startup+b.startup)};});
 return {operator:op.id,name:combo.name,status:'mathematical estimate only; not actual core proof',edges};
}));
const output={'godot/fighting/data/roster.json':{version:1,operators},'godot/fighting/data/rules.json':rules,'port/fighting/content/ANIMATION_COVERAGE.json':manifest,'port/fighting/content/COMBO_ESTIMATES.json':{version:1,assumptions:'First-active-frame contact, shared hitstop, no pushback/landing/projectile travel simulation. Native core verification required.',combos:estimateRows}};
for(const [path,value] of Object.entries(output)){mkdirSync(root+path.slice(0,path.lastIndexOf('/')),{recursive:true});writeFileSync(root+path,JSON.stringify(value,null,2)+'\n');}
const hash=path=>createHash('sha256').update(readFileSync(root+path)).digest('hex');
const moveList=['# Operator Clash — authored move reference','',rules.input_help.notation,'',rules.input_help.simple,'',rules.input_help.guard,'','Frame columns are startup / active / recovery at 60 Hz. Reach is melee box outer edge or maximum projectile travel in metres; mobility rows give displacement cap. Damage is unscaled. These are initial authored targets; human balance and native contacts remain pending.',''];
for(const op of operators){moveList.push(`## ${op.name} (${op.id}) — ${op.archetype}`,'',`HP ${op.stats.hp}; walk ${op.stats.walk_speed} mm/tick; weight ${op.stats.weight}%; jump ${op.stats.jump_velocity} mm/tick. Resource ${op.resource.id}: ${op.resource.initial}/${op.resource.max}.`,'','| Key / input | Original move | S/A/R | Damage | Hit/block stun | Reach m |','|---|---|---:|---:|---:|---:|');for(const [key,m]of Object.entries(op.moves)){const reach=m.projectile?.range??m.throw?.range??m.movement?.distance??Math.max(0,...m.hitboxes.map(b=>b.x+b.w));moveList.push(`| ${key} / ${m.input.simple} | ${m.name} | ${m.startup}/${m.active}/${m.recovery} | ${m.damage} | ${m.hitstun}/${m.blockstun} | ${(reach/1000).toFixed(2)} |`);}moveList.push('');for(const [key,m]of Object.entries(op.moves))moveList.push(`- **${m.name}** (${key}): ${m.description} Counterplay: ${m.counterplay}`);moveList.push('','### Proposed input traces','');for(const combo of op.combos)moveList.push(`- **${combo.name}**: ${combo.route.map(key=>op.moves[key].name).join(' xx ')}. Inputs at ticks ${combo.inputs.map(s=>s.tick).join(', ')}${combo.setup_inputs.length?'; 36-tick back-charge setup from tick 0':''}. ${combo.preconditions.corner?'Airborne corner fixture.':'Grounded close fixture.'} **Pending actual core verification.**`);moveList.push('');}
writeFileSync(root+'port/fighting/content/MOVE_LIST.md',moveList.join('\n')+'\n');
writeFileSync(root+'port/fighting/content/FREEZE.json',JSON.stringify({version:1,date:'2026-10-02',balance:'authored initial targets; human balance pending',combo_validation:'proposed; actual core/native pending',provenance:'Original authored fighting frame data and move names; source operator identities imported unchanged. No downloaded motion or external fighter content.',source_files:Object.fromEntries(['game/data.mjs','port/fighting/DESIGN.md',...Object.keys(output),'port/fighting/content/MOVE_LIST.md','port/fighting/content/CONTRACT_DETAILS.md','tools/fighting/content/author.mjs','tools/fighting/content/validate.mjs'].map(path=>[path,hash(path)]))},null,2)+'\n');
console.log(`Authored ${operators.length} operators, ${operators.reduce((n,op)=>n+Object.keys(op.moves).length,0)} moves, 27 proposed traces.`);
