extends SceneTree

const Router = preload("res://audio/event_router.gd")

func _initialize() -> void:
	var router := Router.new()
	router.start_round("room:4")
	var got := router.consume([{"id":10,"type":"cocs-depot-purchase","team":1,"actor":8}], 8, 0)
	assert(got.is_empty(), "private enemy REQ must never sound")
	got = router.consume([{"id":10,"type":"cocs-depot-purchase","team":1,"actor":8}], 8, 1)
	assert(got.is_empty(), "changing seat/team cannot replay a consumed fact")
	got = router.consume([{"id":11,"type":"cocs-depot-purchase","team":1}], 8, 1)
	assert(got.size() == 1)
	router.start_round("room:4")
	assert(router.consume([{"id":11,"type":"cocs-depot-purchase","team":1}], 8, 1).is_empty(), "same-round reconnect latch")
	assert(router.consume([{"id":12,"sourceId":1,"type":"horde-wave"}], 8).size() == 1)
	assert(router.consume([{"id":13,"sourceId":1,"type":"horde-wave"}], 8).size() == 1, "wire IDs, not payload ordinals")
	assert(router.status().escalation == 2)
	assert(router.consume([{"id":14,"type":"boss-phase"}], 8)[0].escalation == 3)
	assert(router.consume([{"id":15,"type":"horde-wave-cleared"}], 8)[0].escalation == 0)
	assert(router.consume([{"id":16,"type":"vehicle-damage","actor":4,"vehicle":9,"time":3.0,"amount":20}], 8, null, true, 9).size() == 1, "occupant not attacker")
	assert(router.consume([{"id":17,"type":"vehicle-damage","actor":4,"vehicle":9,"time":3.02,"amount":20}], 8, null, true, 9).is_empty(), "50ms hull throttle")
	assert(router.consume([{"id":18,"type":"zone-progress","zone":"A","progress":1}], 8).is_empty())
	assert(router.consume([{"id":19,"type":"zone-progress","zone":"A","progress":25}], 8).size() == 1)
	assert(router.consume([{"id":20,"type":"zone-progress","zone":"A","progress":26}], 8).is_empty())
	router.start_round("room:5")
	assert(router.consume([{"id":11,"type":"cocs-depot-purchase","team":1}], 8, 1).size() == 1, "new round allows reused IDs")
	print("AUDIO_ROUTER_OK")
	quit()
