#!/usr/bin/env node
import {readFileSync,writeFileSync} from 'node:fs';
const replace=(text,from,to)=>{if(text.split(from).length!==2)throw Error(`Scene seam drift: ${from}`);return text.replace(from,to);};
let sports=readFileSync(new URL('../../godot/sports/demo.gd',import.meta.url),'utf8');
sports=replace(sports,'preload("res://world/viewer.gd")','preload("res://multiplayer_worlds/viewer.gd")');
sports=replace(sports,'if not map_id in ["ion-speedway", "aurora-stadium"] or endpoint.is_empty():','if not map_id in ["sirocco-circuit", "copper-bowl"] or endpoint.is_empty():');
sports=replace(sports,'"Require --endpoint=ws://HOST:PORT --map=ion-speedway|aurora-stadium"','"Require a registered Puma world and authority endpoint"');
sports=replace(sports,'mode = "puma-race" if map_id == "ion-speedway" else "puma-soccer"','mode = "puma-race" if map_id == "sirocco-circuit" else "puma-soccer"');
sports=replace(sports,'var endpoint := ""','var endpoint := ""\nvar expected_hash := ""\nvar join_room_id := ""\nvar world_bots := 2');
sports=replace(sports,'if arg.begins_with("--endpoint="): endpoint = arg.trim_prefix("--endpoint=")','if arg.begins_with("--endpoint="): endpoint = arg.trim_prefix("--endpoint=")\n\t\tif arg.begins_with("--join-room="): join_room_id = arg.trim_prefix("--join-room=")\n\t\tif arg.begins_with("--bots="): world_bots = arg.trim_prefix("--bots=").to_int()');
sports=replace(sports,'if not world.load_map(map_id):','if not world.load_map(map_id):');
sports=replace(sports,'audiovisual.configure(self, world.camera, world.catalog.resolve_map(map_id), mode, endpoint)','expected_hash = str(world.catalog.entries[map_id].geometryHash)\n\taudiovisual.configure(self, world.camera, world.catalog.resolve_map(map_id), mode, endpoint)');
sports=replace(sports,'if not configured:\n\t\tconfigured = true','if not configured:\n\t\tconfigured = true\n\t\tif not join_room_id.is_empty(): return');
sports=replace(sports,'var config := {"mode":mode, "botCount":0}','var config := {"mode":mode, "botCount":world_bots}');
sports=replace(sports,'checked(net.configure_match(mode, 0))','checked(net.configure_match(mode, world_bots))');
sports=replace(sports,'func on_started(frame: Dictionary) -> void:\n\taudiovisual.begin','func on_started(frame: Dictionary) -> void:\n\tif str(frame.get("geometryHash", "")) != expected_hash:\n\t\tfail("World geometry differs from authority")\n\t\treturn\n\taudiovisual.begin');
sports=replace(sports,'\t\tfail("World geometry differs from authority")\n\t\treturn\n\taudiovisual.begin','\t\tfail("World geometry differs from authority")\n\t\treturn\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_SPORTS_START ",JSON.stringify({"map":map_id,"mode":mode,"hash":expected_hash,"peer":net.peer_id,"actor":net.actor_id,"room":net.room_id}))\n\taudiovisual.begin');
sports=replace(sports,'state = frame.state\n\tage = 0','state = frame.state\n\tif "--world-evidence" in OS.get_cmdline_user_args() and net.last_ack % 30 == 0: print("WORLD_SPORTS_SNAPSHOT ",JSON.stringify({"map":map_id,"mode":mode,"ack":net.last_ack,"race":state.get("race",{})}))\n\tage = 0');
sports=replace(sports,'\telif frame.get("config") != null and not start_sent:', '\telif frame.get("config") != null and not start_sent:\n\t\tif not join_room_id.is_empty(): return\n\t\tif "--world-fixture-three" in OS.get_cmdline_user_args() and frame.get("players",[]).size() < 3: return');
sports=replace(sports,'func on_results(frame: Dictionary) -> void:\n\ton_snapshot(frame)', 'func on_results(frame: Dictionary) -> void:\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_SPORTS_RESULTS ",JSON.stringify({"map":map_id,"mode":mode,"hash":expected_hash,"peer":net.peer_id,"race":frame.state.get("race",{}),"winner":frame.state.get("winner")}))\n\ton_snapshot(frame)');
sports=replace(sports,'func fail(message: String) -> void:\n\taudiovisual.dropped()', 'func fail(message: String) -> void:\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_SPORTS_ERROR ",message)\n\taudiovisual.dropped()');
sports=replace(sports,'checked(net.create_room())','checked(net.join_room(join_room_id) if not join_room_id.is_empty() else net.create_room())');
const file=new URL('../../godot/multiplayer_worlds/sports_demo.gd',import.meta.url),body='# Generated by tools/godot-multiplayer/generate-scenes.mjs; source sports rules remain unchanged.\n'+sports;
if(process.argv.includes('--check')){if(readFileSync(file,'utf8')!==body)throw Error('Stale sports scene derivative');}else writeFileSync(file,body);
let options=readFileSync(new URL('../../godot/lattice/session_options.gd',import.meta.url),'utf8');
options=replace(options,'const MAPS := ["asterion-relay", "monsoon-foundry"]','const MAPS := ["tern-archipelago"]');
options=replace(options,'"map":"asterion-relay"','"map":"tern-archipelago"');
const latticeOptions=new URL('../../godot/multiplayer_worlds/lattice_options.gd',import.meta.url),latticeOptionsBody='# Generated by tools/godot-multiplayer/generate-scenes.mjs.\n'+options;
if(process.argv.includes('--check')){if(readFileSync(latticeOptions,'utf8')!==latticeOptionsBody)throw Error('Stale LATTICE options');}else writeFileSync(latticeOptions,latticeOptionsBody);
let flow=readFileSync(new URL('../../godot/lattice/session_flow.gd',import.meta.url),'utf8');
flow=replace(flow,'preload("res://lattice/session_options.gd")','preload("res://multiplayer_worlds/lattice_options.gd")');
const flowFile=new URL('../../godot/multiplayer_worlds/lattice_flow.gd',import.meta.url),flowBody='# Generated by tools/godot-multiplayer/generate-scenes.mjs.\n'+flow;
if(process.argv.includes('--check')){if(readFileSync(flowFile,'utf8')!==flowBody)throw Error('Stale LATTICE flow');}else writeFileSync(flowFile,flowBody);
let lattice=readFileSync(new URL('../../godot/lattice/world_demo.gd',import.meta.url),'utf8');
lattice=replace(lattice,'const SessionOptions = preload("res://lattice/session_options.gd")','const SessionOptions = preload("res://multiplayer_worlds/lattice_options.gd")\nconst WorldCatalog = preload("res://multiplayer_worlds/catalog.gd")\nconst WorldMap = preload("res://multiplayer_worlds/map.gd")');
lattice=replace(lattice,'preload("res://lattice/session_flow.gd")','preload("res://multiplayer_worlds/lattice_flow.gd")');
lattice=replace(lattice,'const WORLD_MAPS := ["asterion-relay", "monsoon-foundry"]','const WORLD_MAPS := ["tern-archipelago"]');
lattice=replace(lattice,'client = WorldTransport.new()','client = WorldTransport.new()\n\tcatalog = WorldCatalog.new()');
lattice=replace(lattice,'add_child(environment)\n\tcamera.far = 2000',`add_child(environment)
	# The world scene bypasses the base viewer _ready; establish its own sun and
	# ambient fill so geographic silhouettes and indoor thresholds remain legible.
	sun.rotation_degrees = Vector3(-42,-28,0)
	sun.light_energy = 1.35
	var daylight := Environment.new()
	daylight.background_mode = Environment.BG_COLOR
	daylight.background_color = Color("6a8793")
	daylight.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	daylight.ambient_light_color = Color("a4b3b3")
	daylight.ambient_light_energy = 0.62
	environment.environment = daylight
	camera.far = 2000`);
lattice=replace(lattice,'"Require Asterion/Monsoon and cocs/cocs-coop"','"Require Tern Archipelago and cocs/cocs-coop"');
lattice=replace(lattice,'func on_lobby(frame: Dictionary) -> void:','func on_lobby(frame: Dictionary) -> void:\n\tif "--world-fixture-three" in OS.get_cmdline_user_args() and phase == 12 and frame.get("players",[]).size() >= 3: call_deferred("world_start_requested")\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_LATTICE_LOBBY ",JSON.stringify({"phase":phase,"map":frame.get("mapId"),"mode":frame.get("config",{}),"players":frame.get("players",[]).size()}))');
lattice=replace(lattice,'func on_error(message: String) -> void:','func on_error(message: String) -> void:\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_LATTICE_ERROR ",message)');
lattice=replace(lattice,'world_label.text = "Host lobby · Enter to start"\n\t\tphase = 12','world_label.text = "Host lobby · Enter to start"\n\t\tphase = 12\n\t\tif "--world-evidence" in OS.get_cmdline_user_args() and "--world-fixture-three" not in OS.get_cmdline_user_args(): call_deferred("world_start_requested")');
lattice=replace(lattice,'func on_started(frame: Dictionary) -> void:',`func on_started(frame: Dictionary) -> void:
\tif str(frame.get("geometryHash", "")) != str(catalog.entries[current_id].geometryHash):
\t\ton_error("LATTICE geometry differs from authority")
\t\treturn`);
lattice=replace(lattice,'\t\ton_error("LATTICE geometry differs from authority")\n\t\treturn','\t\ton_error("LATTICE geometry differs from authority")\n\t\treturn\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_LATTICE_START ",JSON.stringify({"map":current_id,"mode":selected_mode,"hash":catalog.entries[current_id].geometryHash,"peer":client.peer_id,"actor":client.actor_id}))');
lattice=replace(lattice,'func on_results(frame: Dictionary) -> void:\n\tav_snapshot(frame.state)', 'func on_results(frame: Dictionary) -> void:\n\tif "--world-evidence" in OS.get_cmdline_user_args(): print("WORLD_LATTICE_RESULTS ",JSON.stringify({"map":current_id,"mode":selected_mode,"peer":client.peer_id,"cocs":frame.state.get("cocs",{}),"winner":frame.state.get("winner")}))\n\tav_snapshot(frame.state)');
lattice+=`
func load_map(id: String) -> bool:
	var data: Dictionary = catalog.recipes.get(id,{})
	if data.is_empty(): return false
	var next := WorldMap.new()
	next.name = "SelectedWorld"
	add_child(next)
	if not next.build(data):
		next.queue_free()
		return false
	if is_instance_valid(world):
		remove_child(world)
		world.free()
	world = next
	current_id = id
	expected_world_hash = str(data.geometryHash)
	return true
`;
lattice=replace(lattice,'var world_error := ""','var world_error := ""\nvar expected_world_hash := ""');
const latticeFile=new URL('../../godot/multiplayer_worlds/lattice_demo.gd',import.meta.url),latticeBody='# Generated by tools/godot-multiplayer/generate-scenes.mjs; source LATTICE rules remain unchanged.\n'+lattice;
if(process.argv.includes('--check')){if(readFileSync(latticeFile,'utf8')!==latticeBody)throw Error('Stale LATTICE scene derivative');}else writeFileSync(latticeFile,latticeBody);
