#!/usr/bin/env node
import {readFileSync,writeFileSync} from 'node:fs';
const replace=(text,from,to)=>{if(text.split(from).length!==2)throw Error(`Scene seam drift: ${from}`);return text.replace(from,to);};
let sports=readFileSync(new URL('../../godot/sports/demo.gd',import.meta.url),'utf8');
sports=replace(sports,'preload("res://world/viewer.gd")','preload("res://multiplayer_worlds/viewer.gd")');
sports=replace(sports,'if not map_id in ["ion-speedway", "aurora-stadium"] or endpoint.is_empty():','if not map_id in ["sirocco-circuit", "copper-bowl"] or endpoint.is_empty():');
sports=replace(sports,'"Require --endpoint=ws://HOST:PORT --map=ion-speedway|aurora-stadium"','"Require a registered Puma world and authority endpoint"');
sports=replace(sports,'mode = "puma-race" if map_id == "ion-speedway" else "puma-soccer"','mode = "puma-race" if map_id == "sirocco-circuit" else "puma-soccer"');
sports=replace(sports,'var endpoint := ""','var endpoint := ""\nvar expected_hash := ""\nvar join_room_id := ""\nvar world_bots := 2');
sports=replace(sports,'if arg.begins_with("--endpoint="): endpoint = arg.trim_prefix("--endpoint=")','if arg.begins_with("--endpoint="): endpoint = arg.trim_prefix("--endpoint=")\n\t\tif arg.begins_with("--join-room="): join_room_id = arg.trim_prefix("--join-room=")\n\t\tif arg.begins_with("--bots="): world_bots = arg.trim_prefix("--bots=").to_int()');
sports=replace(sports,'if not world.load_map(map_id):','if not world.load_map(map_id):');
sports=replace(sports,'audiovisual.configure(self, world.camera, world.catalog.resolve_map(map_id), mode, endpoint)','expected_hash = str(world.catalog.entries[map_id].geometryHash)\n\taudiovisual.configure(self, world.camera, world.catalog.resolve_map(map_id), mode, endpoint)');
sports=replace(sports,'if not configured:\n\t\tconfigured = true','if not configured:\n\t\tconfigured = true\n\t\tif not join_room_id.is_empty(): return');
sports=replace(sports,'var config := {"mode":mode, "botCount":0}','var config := {"mode":mode, "botCount":world_bots}');
sports=replace(sports,'checked(net.configure_match(mode, 0))','checked(net.configure_match(mode, world_bots))');
sports=replace(sports,'func on_started(frame: Dictionary) -> void:\n\taudiovisual.begin','func on_started(frame: Dictionary) -> void:\n\tif str(frame.get("geometryHash", "")) != expected_hash:\n\t\tfail("World geometry differs from authority")\n\t\treturn\n\taudiovisual.begin');
sports=replace(sports,'checked(net.create_room())','checked(net.join_room(join_room_id) if not join_room_id.is_empty() else net.create_room())');
const file=new URL('../../godot/multiplayer_worlds/sports_demo.gd',import.meta.url),body='# Generated by tools/godot-multiplayer/generate-scenes.mjs; source sports rules remain unchanged.\n'+sports;
if(process.argv.includes('--check')){if(readFileSync(file,'utf8')!==body)throw Error('Stale sports scene derivative');}else writeFileSync(file,body);
let options=readFileSync(new URL('../../godot/lattice/session_options.gd',import.meta.url),'utf8');
options=replace(options,'const MAPS := ["asterion-relay", "monsoon-foundry"]','const MAPS := ["tern-archipelago"]');
options=replace(options,'"map":"asterion-relay"','"map":"tern-archipelago"');
const latticeOptions=new URL('../../godot/multiplayer_worlds/lattice_options.gd',import.meta.url),latticeOptionsBody='# Generated by tools/godot-multiplayer/generate-scenes.mjs.\n'+options;
if(process.argv.includes('--check')){if(readFileSync(latticeOptions,'utf8')!==latticeOptionsBody)throw Error('Stale LATTICE options');}else writeFileSync(latticeOptions,latticeOptionsBody);
let lattice=readFileSync(new URL('../../godot/lattice/world_demo.gd',import.meta.url),'utf8');
lattice=replace(lattice,'const SessionOptions = preload("res://lattice/session_options.gd")','const SessionOptions = preload("res://multiplayer_worlds/lattice_options.gd")\nconst WorldCatalog = preload("res://multiplayer_worlds/catalog.gd")\nconst WorldMap = preload("res://multiplayer_worlds/map.gd")');
lattice=replace(lattice,'const WORLD_MAPS := ["asterion-relay", "monsoon-foundry"]','const WORLD_MAPS := ["tern-archipelago"]');
lattice=replace(lattice,'client = WorldTransport.new()','client = WorldTransport.new()\n\tcatalog = WorldCatalog.new()');
lattice=replace(lattice,'"Require Asterion/Monsoon and cocs/cocs-coop"','"Require Tern Archipelago and cocs/cocs-coop"');
lattice=replace(lattice,'func on_started(frame: Dictionary) -> void:',`func on_started(frame: Dictionary) -> void:
\tif str(frame.get("geometryHash", "")) != str(catalog.entries[current_id].geometryHash):
\t\ton_error("LATTICE geometry differs from authority")
\t\treturn`);
lattice+=`
func load_map(id: String) -> bool:
	var data: Dictionary = catalog.recipes.get(id,{})
	if data.is_empty(): return false
	var next := WorldMap.new()
	next.name = "SelectedWorld"
	add_child(next)
	if not next.build(data):
		next.queue_free()
		return false
	if is_instance_valid(world):
		remove_child(world)
		world.free()
	world = next
	current_id = id
	expected_world_hash = str(data.geometryHash)
	return true
`;
lattice=replace(lattice,'var world_error := ""','var world_error := ""\nvar expected_world_hash := ""');
const latticeFile=new URL('../../godot/multiplayer_worlds/lattice_demo.gd',import.meta.url),latticeBody='# Generated by tools/godot-multiplayer/generate-scenes.mjs; source LATTICE rules remain unchanged.\n'+lattice;
if(process.argv.includes('--check')){if(readFileSync(latticeFile,'utf8')!==latticeBody)throw Error('Stale LATTICE scene derivative');}else writeFileSync(latticeFile,latticeBody);
