import fs from 'node:fs';
import {createHash} from 'node:crypto';
const evidence='/home/mojo/.tmp-on-disk/cocs-new-map-foundry-evidence-20261002';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const write=(p,d)=>fs.writeFileSync(p,JSON.stringify(d,null,2)+'\n');
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const data=read('godot/multiplayer_worlds/generated/gravemill-foundry.json'),geometryHash=data.geometryHash;
const prefix=(file,tag)=>fs.readFileSync(file,'utf8').split('\n').filter(s=>s.startsWith(tag)).map(s=>JSON.parse(s.slice(tag.length)));
const source=read(`${evidence}/revision-02/source-check.json`),rounds=read(`${evidence}/revision-02/round-check-payload-assault-domination-combined-arms-deathmatch-teamdeathmatch.json`),bots=read(`${evidence}/revision-02/bot-check.json`),art=read(`${evidence}/blender-inlay-final/blender-budget.json`);
const physics=prefix(`${evidence}/physics-attempt-01.log`,'GRAVEMILL_PRODUCTION_PHYSICS_OK ')[0];
const modes=['payload','assault','combined-arms','deathmatch','teamdeathmatch','domination'];
const native=modes.map(mode=>read(`${evidence}/native-final/${mode}-result.json`));
for(const receipt of [source,rounds,bots,art,physics,...native])if(receipt?.geometryHash!==geometryHash)throw Error('Missing or mismatched proof hash');
if(physics.routeCapsules!==908||physics.routeSupportRays!==908||physics.wallContactSteps!==160)throw Error('Missing physics probes');
const reopen=prefix(`${evidence}/blender-inlay-reopen.log`,'GRAVEMILL_MASTER_REOPEN ')[0];
if(reopen?.geometryHash!==geometryHash)throw Error('Missing master reopen');
const local='port/new-maps/gravemill-foundry';
write(`${local}/source-validation.json`,{source,rounds});write(`${local}/bot-validation.json`,bots);
const summarized=native.map(({mode,label,seconds,wallSeconds,controls,distanceMoved,mounted,exited,driveDistance,teamScores,kills,nativeReceipts})=>({mode,label,seconds,wallSeconds,controls,distanceMoved,mounted,exited,driveDistance,teamScores,kills,nativeReceipts}));
write(`${local}/native-validation.json`,{geometryHash,physics,rounds:summarized,fixtureLimit:'Controlled normal-input native peers with passive opponent; autonomous bot observations recorded separately',evidence});
const walkthrough=read(`${evidence}/native-visual-final/walkthrough-result.json`),walkClip=read(`${evidence}/native-visual-final/walkthrough-clip.json`);
if(walkthrough.geometryHash!==geometryHash||walkClip.geometryHash!==geometryHash)throw Error('Visual proof hash mismatch');
const views=prefix(`${evidence}/native-inspection-attempt-04.log`,'FOUNDRY_NATIVE_VIEW ');
const visual={geometryHash,walkthrough:{seconds:walkthrough.seconds,wallSeconds:walkthrough.wallSeconds,controls:walkthrough.controls,distanceMoved:walkthrough.distanceMoved,stages:walkthrough.stages},walkClip,views,inspectedStills:['overview','crusher-eye','cooling-eye','assay-eye','crown-eye','furnace-eye'].map(name=>({path:`${evidence}/native-reviewed/${name}.png`,sha256:sha(`${evidence}/native-reviewed/${name}.png`)}))};
const payloadVisual=`${evidence}/native-payload-visual-final/payload-result.json`,payloadClip=`${evidence}/native-payload-visual-final/payload-clip.json`;
if(fs.existsSync(payloadVisual)&&fs.existsSync(payloadClip)){const p=read(payloadVisual);if(p.geometryHash!==geometryHash)throw Error('Payload visual hash mismatch');visual.payload={seconds:p.seconds,controls:p.controls,nativeReceipts:p.nativeReceipts,objective:p.objective,clip:read(payloadClip)};}
write(`${local}/visual-validation.json`,visual);
write('godot/multiplayer_worlds/art/gravemill-foundry/gravemill-foundry-art-report.json',art);
const assets=['tools/godot-multiplayer/new-maps/gravemill-foundry/gravemill-foundry.blend','godot/multiplayer_worlds/art/worlds/gravemill-foundry.glb','tools/godot-multiplayer/new-maps/gravemill-foundry/recipe.mjs','tools/godot-multiplayer/new-maps/gravemill-foundry/blender.py'];
write(`${local}/provenance.json`,{id:data.id,geometryHash,recipeHash:data.recipeHash,seed:data.arena.seed,masterReopen:reopen,assets:assets.map(path=>({path,sha256:sha(path),bytes:fs.statSync(path).size})),sourceModules:['game/core.mjs','game/terrain.mjs','game/vehicles.mjs','port/multiplayer-worlds/derived/core.mjs'].map(path=>({path,sha256:sha(path)})),evidence});
write(`${local}/capabilities.json`,{id:data.id,name:data.name,stage:'SOURCE AND NATIVE PROVEN',accepted:true,geometryHash,recipeHash:data.recipeHash,nativeColliderHash:physics.geometryHash,blenderStatus:'generated and reopened; eight authored cameras, four final-build CPU renders; production native views inspected',modes:Object.fromEntries(modes.map(mode=>[mode,{sourceFullRound:'passed',nativeJourney:'passed',publicPlayable:true}])),fixtureLimit:'controlled native full rounds; bounded autonomous source bots separately documented; no competitive-balance or GPU-performance claim',evidence});
console.log(JSON.stringify({geometryHash,nativeModes:modes,sourceNodes:source.results.find(r=>r.name==='source-navigation').nodes,artTriangles:art.triangles,physicsTriangles:physics.metrics.gameplayTriangles}));
