"""Remove only S-generated unrelated sidecars, recording every byte identity."""
import json
import subprocess
from grant import HERE,ROOT,sidecars,write,now
before=json.loads((HERE/'evidence/attempts/sidecars-before.json').read_text());current=sidecars()
write(HERE/'evidence/attempts/sidecars-precleanup.json',current)
changed={p:{'before':h,'after':current.get(p)} for p,h in before.items() if current.get(p)!=h}
assert not changed,('Tracked/baseline sidecar mutation requires investigation',changed)
tracked=set(subprocess.check_output(['git','ls-files'],cwd=ROOT,text=True).splitlines())
removed={}
for p,h in current.items():
 if p in before or p in tracked or '/gravemill_foundry/revision5/' in p or 'gravemill-foundry-r5' in p:continue
 assert p.endswith(('.uid','.import'))
 (ROOT/p).unlink();removed[p]=h
write(HERE/'evidence/attempts/sidecar-cleanup.json',{'time':now(),'baselineChanges':changed,'removedOwnedGeneratedUnrelated':removed,
 'reason':'Fresh isolated worktree; these absent-before untracked sidecars were generated by S import. R5 closure retained; no source/restamp rewrite.'})
print('S sidecars: baseline unchanged; removed only generated unrelated sidecars',len(removed))
