// Single generated ownership for route capability facts (NATIVE-03).
//
// Nothing here hand-maintains a per-experience map/mode/authority roster. Every
// accepted map/mode and every authority fact is observed by running the
// authoritative options() parser. The locked catalog + NATIVE_ARENA_MAPS and
// the EXPERIENCES/NATIVE_EXPERIENCES tables are reused only as the candidate
// input and as the fixed 22-route identity.
//
// Consumers:
//   - gen_routes.mjs writes the derived facts into godot/ui/routes.json
//     (`route.capability`); godot/ui/route_registry.gd validates and exposes
//     them so the menu shares one generated authority description.
//   - route_parity.test.mjs re-derives the facts from BOTH the packaged
//     options() parser and the dev launchOptions() parser over every registered
//     route choice, so either parser drifting fails the gate.
//
// Deliberate remaining dedup (documented, not migrated here): the dev launcher
// tools/godot-dev/launch_options.mjs keeps its own EXPERIENCES table and
// validation because ownership fixtures copy only launch_options.mjs +
// endpoint.mjs into a scratch package. Feeding the generated registry into
// those fixtures is a follow-up; until then the parity gate holds both parsers
// to the same generated capability facts, and the dev launcher only gains the
// two parameterless scenes routes.json already declares.

export const AUTHORITY_KEYS = ['offline', 'local', 'external'];

// Candidate map ids in catalog order, then the reviewed native arenas the
// catalog intentionally omits. Reused by the generator and the parity gate so
// neither invents its own list.
export function candidateMaps(catalog, nativeArenaMaps) {
  const ids = catalog.maps.map(map => map.id);
  const seen = new Set(ids);
  for (const id of nativeArenaMaps) if (!seen.has(id)) { seen.add(id); ids.push(id); }
  return ids;
}

// Candidate mode vocabulary referenced by the authoritative experience tables
// (locked maps plus the reviewed identity entries). The parser can only ever
// accept a mode named by one of these tables, so this stays a projection of the
// existing roster rather than a second one.
export function candidateModes(experiences) {
  const modes = new Set();
  for (const entry of Object.values(experiences)) {
    for (const list of Object.values(entry.maps ?? {})) for (const mode of list) modes.add(mode);
    for (const identity of Object.values(entry.identity ?? {})) for (const mode of identity.modes) modes.add(mode);
  }
  return [...modes];
}

const accepts = (parse, catalog, argv) => {
  try { parse(argv, catalog); return true; } catch { return false; }
};

// Reachable map/mode scope observed from the parser. Lists are sorted so the
// generated bytes stay deterministic; player-facing ordering lives in params.
export function scopeOf(parse, catalog, baseArgs, {maps, modes}) {
  const accepted = new Map();
  for (const map of maps) {
    const reachable = modes.filter(mode => accepts(parse, catalog, [...baseArgs, `--map=${map}`, `--mode=${mode}`]));
    if (reachable.length) accepted.set(map, reachable);
  }
  const orderedMaps = [...accepted.keys()].sort();
  const modesByMap = {};
  for (const map of orderedMaps) modesByMap[map] = [...accepted.get(map)].sort();
  return {maps: orderedMaps, modes_by_map: modesByMap};
}

// Parser defaults for the route (the menu's declared defaults must match these).
export function defaultsOf(parse, catalog, baseArgs) {
  const plan = parse(baseArgs, catalog);
  return {map: plan.map ?? null, mode: plan.mode ?? null};
}

// Authority ownership observed from actual plans. `local` means an
// endpoint-free plan owns a loopback authority; `external` means --endpoint is
// accepted and, when supplied, the launcher reuses it and never constructs a
// local authority (run.mjs/launch.mjs guard `plan.nativeOnly || plan.endpoint`).
// `offline` means the route runs with no authority and no source match at all.
export function authorityOf(parse, catalog, baseArgs) {
  const localPlan = parse(baseArgs, catalog);
  const offline = localPlan.nativeOnly === true;
  const endpoint = 'ws://127.0.0.1:12345';
  let external = false;
  try { external = parse([...baseArgs, `--endpoint=${endpoint}`], catalog).endpoint === endpoint; } catch {}
  return {offline, local: !offline, external};
}

export function capabilityOf(parse, catalog, baseArgs, candidates) {
  return {
    authority: authorityOf(parse, catalog, baseArgs),
    scope: scopeOf(parse, catalog, baseArgs, candidates),
    defaults: defaultsOf(parse, catalog, baseArgs),
  };
}

// Shape guard shared by the generator and the Node parity gate. The Godot
// registry mirrors the same rules (route_registry.gd:validate_capability_shape).
export function capabilityShapeErrors(capability, context) {
  const where = context ? `${context}: ` : '';
  const errors = [];
  if (!capability || typeof capability !== 'object' || Array.isArray(capability)) {
    return [`${where}capability is not an object`];
  }
  const authority = capability.authority;
  if (!authority || typeof authority !== 'object' || Array.isArray(authority)) {
    errors.push(`${where}capability.authority is not an object`);
  } else {
    for (const key of AUTHORITY_KEYS) {
      if (typeof authority[key] !== 'boolean') errors.push(`${where}authority.${key} is not a boolean`);
    }
    if (authority.offline === true && (authority.local === true || authority.external === true)) {
      errors.push(`${where}offline authority cannot also be local or external`);
    }
    if (authority.offline === false && authority.local === false && authority.external === false) {
      errors.push(`${where}non-offline route declares no authority ownership`);
    }
  }
  const scope = capability.scope;
  if (!scope || typeof scope !== 'object' || Array.isArray(scope)) {
    errors.push(`${where}capability.scope is not an object`);
  } else {
    const maps = scope.maps;
    const byMap = scope.modes_by_map;
    if (!Array.isArray(maps)) errors.push(`${where}scope.maps is not an array`);
    if (!byMap || typeof byMap !== 'object' || Array.isArray(byMap)) {
      errors.push(`${where}scope.modes_by_map is not an object`);
    } else if (Array.isArray(maps)) {
      for (const map of maps) {
        if (!Object.hasOwn(byMap, map)) errors.push(`${where}scope map ${map} has no modes`);
        else if (!Array.isArray(byMap[map]) || byMap[map].length === 0) {
          errors.push(`${where}scope modes for ${map} are empty`);
        }
      }
      for (const map of Object.keys(byMap)) if (!maps.includes(map)) {
        errors.push(`${where}scope modes_by_map references undeclared map ${map}`);
      }
    }
  }
  const defaults = capability.defaults;
  if (!defaults || typeof defaults !== 'object' || Array.isArray(defaults)) {
    errors.push(`${where}capability.defaults is not an object`);
  } else {
    const scopeMaps = capability.scope?.maps;
    if (defaults.map !== null && (!Array.isArray(scopeMaps) || !scopeMaps.includes(defaults.map))) {
      errors.push(`${where}defaults.map ${defaults.map} is outside the observed scope`);
    }
    if (defaults.mode !== null && defaults.map !== null && capability.scope?.modes_by_map?.[defaults.map]
      && !capability.scope.modes_by_map[defaults.map].includes(defaults.mode)) {
      errors.push(`${where}defaults.mode ${defaults.mode} is not reachable on ${defaults.map}`);
    }
  }
  return errors;
}
